:toc:
:toclevels: 6

== What is yellow pages
=== Present day Problem?
* if user want information in xls tabular format, (Eg: All dental hospitals in marathalli, Bangalore). He will be presented multiple websites or google search results(which are not accurate).
* There are multiple busineses(Eg: automobile, grocery) which are even not listed.

=== Solution
* Presenting yellow pages, which will take input from user and based on category will provide address,rating,phone number in tabular format. With this user can directly dial a phone number and reach the business.
* AI model will generate comparison chart for customer ratings, user reviews etc.

== 1. Requirements
=== Functional
* 1. Friendly UI(web and mobile)

[[set_business_info]]
* 2. *Business owner save business information to system:* From UI(maybe antd) Business information(country,state,area,category..) into DB.

[[get_business_info]]
* *3. Customer can search Businesses information:* UI(maybe antd), taking input from user & calling REST APIs of application_server(microservice) running on AWS central(region) then provide info to user.
** a. Get businesses (country,state,area,category=hospitals,subcategory=dental) information
** Options to take user input
*** a. Option-1: Text box (hospitals near me)
*** b. Option-2: 4-5 dropdowns

=== Extended
* 1. AI model to generate comparison charts based on customer reviews etc.

* 2. User registration, this will used for authentic reviews.

* 3. Data Validation. Ensure business data is authentic & cleaning required on periodic basis.

link:https://docs.google.com/document/d/1a8nwbQII8LqIQlF5NEk2cyviRNx15zgvtY672yCCOP4/edit?usp=sharing[Diagram]

=== Non-Functional
* 1. Highly available
* 2. Fast
* 3. Display relevant results(sorted by nearest)
* 4. Results should not be stale

== 2. API Design (API for every requirement)
* 2. <<set_business_info, Business owner can save Business information>>
```c
pub const SET_BUSINESS_INFO:&str = "/query/v1/set_business_info/{country}/{state}/{region}/{category}/{name}";

// Listen on REST end-point
let server = HttpServer::new (||{
  .service (web::resource(SET_BUSINESS_INFO).route(web::post().to(Self::set_business_information))
});
```

* 3. <<get_business_info, Get Business information>>
```c
pub const GET_BUSINESS_INFO:&str = "/query/v1/get_business_info/{country}/{state}/{region}/{category}";

// Listen on REST end-point
let server = HttpServer::new (||{
  .service (web::resource(GET_BUSINESS).route(web::get().to(Self::get_business_information))
});

// Function doing business logic
get_business_information() {
  - Parse country, state, region etc
  - Read info from in memory cache (if present)
}
```

== 3. DB Schema
* Let's identify entities in system.
* a. business_table: Have list of all businesses
```c
|business-id(primary key)|name|category|location-id(foriegn key)|phone number|Email|Esclation-Email|website|
|Description|Hours of Operation|Rating|Creation Date|Last Updated at|Verification Status|
```
* b. user_table: All registered users
```c
|user-id(primary key)|name(optional)|username|password(hashed, salted)|email|profile info|
```
* c. reviews_table: All reviews given by users to business
```c
|review-id(primary key)|business-id(foriegn-key)|user-id|rating|text|Review Date|
// Review can have image as well, which is stored in review_image table with image-id mapped to review-id
```
* d. review_image_table
```c
|image-id(primary key)|review0id(foriegn key)|description|image_url|upload date|
```
* e. Categories Table: This table defines the categories of businesses available on the platform.
```c
|Category ID (Primary Key)|Category Name|Category Description|
```
* f. location table: Stores geographic information, which is helpful for location-based searches.
```c
|Location ID (Primary Key)|City|State|Zip Code|Latitude and Longitude (for mapping and distance calculations)|
```
* g. Business Owners Table (if business owners can claim their listings)
```c
|Business Owner ID (Primary Key)|User ID (linked to the User Table)|Business ID (linked to the Businesses Table)|Claim Status|
```

== 4. HLD
