:toc:
:toclevels: 6

== link:https://leetcode.com/problems/maximize-happiness-of-selected-children[3075. Maximize Happiness of Selected Children]
You are given an array happiness of length n, and a positive integer k.

There are n children standing in a queue, where the ith child has happiness value happiness[i]. You want to select k children from these n children in k turns.

In each turn, when you select a child, the happiness value of all the children that have not been selected till now decreases by 1. Note that the happiness value cannot become negative and gets decremented only if it is positive.

Return the maximum sum of the happiness values of the selected children you can achieve by selecting k children.
```c
Example 1:
Input: happiness = [1,2,3], k = 2
Output: 4
Explanation: We can pick 2 children in the following way:
- Pick the child with the happiness value == 3. The happiness value of the remaining children becomes [0,1].
- Pick the child with the happiness value == 1. The happiness value of the remaining child becomes [0]. Note that the happiness value cannot become less than 0.
The sum of the happiness values of the selected children is 3 + 1 = 4.

Example 2:
Input: happiness = [1,1,1,1], k = 2
Output: 1
Explanation: We can pick 2 children in the following way:
- Pick any child with the happiness value == 1. The happiness value of the remaining children becomes [0,0,0].
- Pick the child with the happiness value == 0. The happiness value of the remaining child becomes [0,0].
The sum of the happiness values of the selected children is 1 + 0 = 1.

Example 3:
Input: happiness = [2,3,4,5], k = 1
Output: 5
Explanation: We can pick 1 child in the following way:
- Pick the child with the happiness value == 5. The happiness value of the remaining children becomes [1,2,3].
The sum of the happiness values of the selected children is 5.
```

== Rephrased Statement
* Add k maximum elements from the array, after selecting a maximum element reduce value of remanining elements in array by 1.
* Only add element to sum if its positive

== Approach-1. Time: O(n), Space: O(n)
=== Logic
* Fill elements in max_heap
```c
 max_heap = [3,2,1], k =2
```
* Take a variable temp, which decrements everytime by 1, when element is poped from queue.

=== Code
==== CPP
```cpp
class Solution {
public:
    long long maximumHappinessSum(vector<int>& happiness, int k) {
        priority_queue<int> max_heap;
        for (auto&i:happiness)
            max_heap.push(i);
        long long top = max_heap.top(), out = 0, temp = 0;

        while (top>0 && !max_heap.empty() && k>0) {
            int present_hapiness = max_heap.top() + temp;
            if (present_hapiness < 1)
                break;
            out += present_hapiness;
            --temp;
            --k;
            max_heap.pop();
        }
        return out;
    }
};
```
