:toc:
:toclevels: 6

== Advantages of XML
- **Interoperatability:** 2 applications written in different languages can communicate easily using XML.
- **Meta-data** data about data is represented clearly wrt plain text.

== Terms
=== link:https://www.w3.org/TR/DOM-Level-3-Core/introduction.html[DOM(Document Object Model)]
* DOM is tree like structure.
* The nodes are defined by their relationship to other DOM nodes. Some elements are parents of child nodes, and child nodes have siblings.
* DOM is framework of defininig XML/html document using trees/forests. Xerces is based on DOM. In DOM each element is called object(having functions and identity).
* DOM takes huge memory. To parse 1MB XML it takes around 5MB RAM.

==== XML DOM representation
```xhtml
<table>
  <tbody> 
    <tr> 
      <td>Shady Grove</td>
      <td>Aeolian</td> 
    </tr> 
    <tr>
      <td>Over the River, Charlie</td>        
      <td>Dorian</td> 
    </tr> 
  </tbody>
</table>

<?xml version="1.0" encoding="UTF-8"?>        //XML Version
<note>                                        //Root Element
  <to>Tove</to>                               //Child Elements: to, from, heading, body
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>                                        //Root Element End. Closing Tag is Must
```

==== html DOM representation
```html
// This HTML doc is represented by below DOM
<p>
  Let's use:
  <span>Cascading</span>
  <span>Style</span>
  <span>Sheets</span>
</p>

// DOM representation
P
├─ "Let's use:"
├─ SPAN
|  └─ "Cascading"
├─ SPAN
|  └─ "Style"
└─ SPAN
    └─ "Sheets"
```
=== DTD / Document Type Definition
Both DTD & XML Schemas describe strucuture of XML document and what data is allowed.
- _XML Validation:_ DTD and schema can be used to validate XML document that doc recived is as per prescribed format or not.
- _DTD vs XML Schemas:_ DTD is older standard wrt XML schemas. XML schemas are easy an offer more functionality. Most tools use XML schemas now.

=== XML Namespace
Name conflicts in XML is used to avoid name conflict. It uses name prefix.
```xml
<h:table>
  <h:tr>
    <h:td>Apples</h:td>
    <h:td>Bananas</h:td>
  </h:tr>
</h:table>

<f:table>
  <f:name>African Coffee Table</f:name>
  <f:width>80</f:width>
  <f:length>120</f:length>
</f:table>
```

=== XML XPath
Complete path of element in XML document. XPath of 1st book=`/bookstore/book[0]`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<bookstore>
<book category="cooking">
  <title lang="en">Everyday Italian</title>
  <author>Howdy</author>
  <year>2005</year>
  <price>30.00</price>
</book>
</bookstore>
```

=== XSLT (eXtensible Stylesheet Language Transformations)
XSLT is [sylesheet language](/Languages/StyleSheetLanguage) for XML. XSLT is used for transforming XML doc to HTML. Example
```xml
//XML doc
<?xml version="1.0" encoding="UTF-8"?>
<breakfast_menu>
  <food>
    <name>Pasta</name>
    <price>$5.95</price>
    <calories>650</calories>
  </food>
</breakfast_menu>

//XSLT stylesheet doc
<?xml version="1.0" encoding="UTF-8"?>
  <html xsl:version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <body style="font-family:Arial;font-size:12pt;background-color:#EEEEEE">
      <xsl:for-each select="breakfast_menu/food">
        <div style="background-color:teal;color:white;padding:4px">
        <span style="font-weight:bold"><xsl:value-of select="name"/> - </span>
      <xsl:value-of select="price"/>
    <div style="margin-left:20px;margin-bottom:1em;font-size:10pt">
      <p>
        <xsl:value-of select="description"/>
        <span style="font-style:italic"> (<xsl:value-of select="calories"/> calories per serving)</span>
      </p>
    </div>
  </xsl:for-each>
  </body>
</html>
```

=== XQuery
Querying XML document data using query statements. Xquery us similar to SQL in DB.
```xml
for $x in doc("books.xml")/bookstore/book
where $x/price>30
order by $x/title
return $x/title
```

=== CDATA(Character data) Section
Anything inside cdata section is considered text not markup.
```xml
<conversionData><![CDATA[
  i Kilometer &it; 1 mile
]]></conversionData>  
```

== XML Parsers
```c
                    Name            |   About
------------------------------------|-----------------------
MSXML(Microsoft Core XML services)  | Microsoft's XML tool(including parser), exposed as COM object, accessed using C++ also.
System.Xml.XmlDocument              | In Microsoft .Net library. Has all standard DOM features.
Saxon                               | Micheal Kay's product for XML parsing, quering, transforming. In java & .net
Xerces                              | In java and c++ by Apache open source
```

== Rules for creating XML Doc
**Well Formed XML?** A document that follows W3C's XML Recommendataions and rules laid by is called well-formed xml else that is just a text document.
- See Naming convention of elements at W3C.
- [Elements & Attributes](..)
```xml
<?xml version="1.0"?>         //XML Prolog(Optional): contains version(1.0 or 1.1), encoding(optional), standalone(optional)
<person>                      //Root Element. There should be 1 and only 1 root element. Every element follows naming convention.
  <name> Amit </name>         //Child elements follow naming conventions. Content cannot have &(reference), <()
  <address> abc </address>
</person>

OR 

<?xml version="1.0"?>           //This is also valid XML
<person>        
  <name Amit ></name>
  <address abc ></address>
</person>

```
