:toc:
:toclevels: 4

=== link:https://leetcode.com/problems/coin-change-2[518. Coin Change II]
- You are given coins of different denominations and a total amount of money. Find number of combinations that make up that amount. There is infinite number of each kind of coin.
- Examples
```c
Example-1
Input: amount = 5, coins = [1, 2, 5]
Output: 4
Explanation: there are four ways to make up the amount:
5=5
5=2+2+1
5=2+1+1+1
5=1+1+1+1+1
Example 2:

Example-2
Input: amount = 3, coins = [2]
Output: 0
Explanation: the amount of 3 cannot be made up just with coins of 2.
```


=== Approach-1. Backtracking. TLE
==== Why TLE?
* Solving using backtracking, it's likely to be less efficient and more difficult to implement correctly due to the exponential nature of the problem space

=== Approach-2. Dynamic Programming
==== Why DP?
===== Overlapping subproblems
* Here we need to calculate the number of combinations for different amounts of money. 
* As we break down the problem into smaller subproblems (using different coin denominations), you'll find that there's a significant amount of overlap in the subproblems. 

===== Optimal substructure
* solution to a larger problem can be built using solutions to smaller subproblems.
* This involves reusing previously computed solutions to subproblems

==== LOGIC
* Watch Videos for explanation, because its pretty complex. link:https://youtu.be/7pRO5Zuiijo[Self-Youtube-Video] link:https://youtu.be/C8bmCYohJkw[Video2]
* 1. How this is DP Problem(overlapping subproblems)
```c
coins =[1, 2, 5], target=5
Provided coins    No of ways to make 5
     1            1 (1+1+1+1+1)
     2            0
     1,2           No of ways to make 5 using only 1  =  1                  //Overlapping subproblem
                  +No of ways to make 5 using only 2  =  0                  //Overlapping subproblem
                  +No of ways to make 5 using only (1,2) = 2(1+1+1+2, 1+2+2)
                  = 3
    1,2,5          No of ways to make 5 using only 1  =  1      //already calculated
                  +No of ways to make 5 using only 2  =  0      //already calculated
                  +No of ways to make 5 using only 5  =  1
                  +No of ways to make 5 using only 1,2  =  3    //already calculated
                  = 5
```
* 2. We will take DP array. coins=[1,2,3]. target=5
```c
Provided Coins    No of ways to create 1,2,3,5 --->
    \/            1    2    3    4    5
    1
    2
    3                                answer
```

==== Code
===== CPP
```cpp
int beforeMain() {			//Speeds up cout.
	ios_base::sync_with_stdio( false );
  cin.tie(NULL);
  return 0;
}

int static r = beforeMain();		//Call function before main

#define endl '\n';

class Solution {
public:
    int change(int amount, vector<int>& coins) {

      if (amount == 0)
        return 1;
      if (amount && coins.size() == 0)
        return 0;        

      sort(coins.begin(), coins.end());

      int num_of_coins = coins.size();

      /*
      This is 2D Dynamic Programming Array representing no of ways to
      form denomination from given coins
      - Every entry represents number of ways denomination can be formed
      rows represents number of coins of each type. (num_of_coins)
      cols represents no of ways amount can be formed from given coins (amount+1)
      if we have 3 coins(1,2,3) and amount = 4. dp[3][5]
          0 1 2 3 4
        1
        2
        3
      */
      vector<vector<int>> dpways(num_of_coins, vector(amount+1,0));
      dpways[0][0] = 1;

      // Fill 1st row
      for (int i=0; i<amount+1; i++)
        i%coins[0] ? dpways[0][i] = 0 : dpways[0][i] = 1;
        // if (i%coins[0] == 0)
        //   dpways[0][i] = 1;
        // else
        //   dpways[0][i] = 0;

      // Fill 1st col
      for (int i=0;i<num_of_coins;i++)
        dpways[i][0] = 1;

      for (int i=1;i<num_of_coins;i++) {
        for (int j=1;j<amount+1;j++){
          j < coins[i] ? dpways[i][j] = dpways[i-1][j] : dpways[i][j] = dpways[i-1][j] + dpways[i][j - coins[i]];
          // if(j < coins[i])
          //   dpways[i][j] = dpways[i-1][j];
          // else
          //   dpways[i][j] = dpways[i-1][j] + dpways[i][j - coins[i]];
        }
      }
      return dpways[num_of_coins-1][amount];        
    }
};
```

==== Python
```py
class Solution:
    def change(self, amount: int, coins: List[int]) -> int:
      if amount == 0:
        return 1
      if amount and len(coins)==0:
        return 0
      
      coins.sort()
      num_of_coins = len(coins)

      """
      This is 2D Dynamic Programming Array representing no of ways to
      form denomination from given coins
      - Every entry represents number of ways denomination can be formed
      rows represents number of coins of each type. (num_of_coins)
      cols represents no of ways amount can be formed from given coins (amount+1)
      if we have 3 coins(1,2,3) and amount = 4. dp[3][5]
          0 1 2 3 4
        1
        2
        3
      """
      #dpways = [[0 for _ in range(cols)] for _ in range(rows)]
      dpways = [[0 for _ in range(amount+1)] for _ in range(num_of_coins)]
      dpways[0][0] = 1

      # Fill 1st row
      for i in range (0, amount+1):
        if i%coins[0] == 0:
          dpways[0][i] = 1
        else:
          dpways[0][i] = 0

      # Fill 1st col
      for i in range(0, num_of_coins):
        dpways[i][0] = 1

      for i in range(1, num_of_coins):
        for j in range(1, amount+1):
          if j < coins[i]:
            dpways[i][j] = dpways[i-1][j]
          else:
            dpways[i][j] = dpways[i-1][j] + dpways[i][j - coins[i]]

      # Last element of matrix is the answer
      return dpways[num_of_coins-1][amount]
```
