:toc:
:toclevels: 3

== link:https://leetcode.com/problems/remove-outermost-parentheses/[1021. Remove Outermost Parentheses]
A valid parentheses string is either empty "", "(" + A + ")", or A + B, where A and B are valid parentheses strings, and + represents string concatenation.

- For example, "", "()", "(())()", and "(()(()))" are all valid parentheses strings.
- A valid parentheses string s is primitive if it is nonempty, and there does not exist a way to split it into s = A + B, with A and B nonempty valid parentheses strings.

Given a valid parentheses string s, consider its primitive decomposition: s = P1 + P2 + ... + Pk, where Pi are primitive valid parentheses strings.

Return s after removing the outermost parentheses of every primitive string in the primitive decomposition of s.

 
```
Example 1:
Input: s = "(()())(())"
Output: "()()()"
Explanation: 
The input string is "(()())(())", with primitive decomposition "(()())" + "(())".
After removing outer parentheses of each part, this is "()()" + "()" = "()()()".

Example 2:
Input: s = "(()())(())(()(()))"
Output: "()()()()(())"
Explanation: 
The input string is "(()())(())(()(()))", with primitive decomposition "(()())" + "(())" + "(()(()))".
After removing outer parentheses of each part, this is "()()" + "()" + "()(())" = "()()()()(())".

Example 3:
Input: s = "()()"
Output: ""
Explanation: 
The input string is "()()", with primitive decomposition "()" + "()".
After removing outer parentheses of each part, this is "" + "" = "".
```

== Approach
- Iterate over string and take 2 pointers, start, end.
- Count open, close brackets.
- When count_of_open_brackets == count_of_close_brackets take substring between end brackets and move pointers.

== Complexity
- Time complexity: O(n)
- Space complexity: O(1)

== Code
=== CPP
```cpp
class Solution {
public:
    string removeOuterParentheses(string s) {
        int sptr = 0, eptr = 0, openC = 0, closeC = 0;
        string out = "";
        for (int i=0;i<s.size();i++) {
            if (s[i] == '(')
                openC++;
            else
                closeC++;
            if (openC == closeC) {
                // Remove external brackets
                out += s.substr(sptr+1, eptr-sptr-1);
                openC = closeC = 0;
                sptr = eptr+1;
            }
            eptr++;
        }
        return out;
    }
};
```

=== Go
```go
func removeOuterParentheses(s string) string {
    out := []string{}
    sptr := 0
    eptr := 0
    openC := 0
    closeC := 0

    for _, value := range s {
        if value == '(' {
            openC += 1
        } else {
            closeC += 1
        }
        if (openC == closeC) {
                // Remove external brackets
                out = append(out, s[sptr+1:eptr])
                openC = 0
                closeC = 0
                sptr = eptr+1
        }
        eptr += 1
    }
    return strings.Join(out, "")
}
```
