:toc:
:toclevels: 4

== link:https://leetcode.com/problems/maximum-nesting-depth-of-two-valid-parentheses-strings[1111. Maximum Nesting Depth of Two Valid Parentheses Strings]
A string is a valid parentheses string (denoted VPS) if and only if it consists of "(" and ")" characters only, and:

It is the empty string, or
It can be written as AB (A concatenated with B), where A and B are VPS's, or
It can be written as (A), where A is a VPS.
We can similarly define the nesting depth depth(S) of any VPS S as follows:

depth("") = 0
depth(A + B) = max(depth(A), depth(B)), where A and B are VPS's
depth("(" + A + ")") = 1 + depth(A), where A is a VPS.
For example, "", "()()", and "()(()())" are VPS's (with nesting depths 0, 1, and 2), and ")(" and "(()" are not VPS's.

Given a VPS seq, split it into two disjoint subsequences A and B, such that A and B are VPS's (and A.length + B.length = seq.length). The subsequences may not necessarily be contiguous.

For example, for the sequence 123456789, one possible split is:

A = {1, 3, 5, 7, 9},

B = {2, 4, 6, 8}.

This corresponds to the output [0, 1, 0, 1, 0, 1, 0, 1, 0]  where 0 indicates membership in A and 1 indicates membership in B.

Now choose any such A and B such that max(depth(A), depth(B)) is the minimum possible value.

Return an answer array (of length seq.length) that encodes such a choice of A and B:  answer[i] = 0 if seq[i] is part of A, else answer[i] = 1.  Note that even though multiple answers may exist, you may return any of them.

```
Example 1:
Input: seq = "(()())"
Output: [0,1,1,1,1,0]

Example 2:
Input: seq = "()(())()"
Output: [0,0,0,1,1,0,1,1]
```

== Approach
- Assign all even depths to Group A = 0
- Assign all odd depths to Group B = 1

== Code
=== CPP
```cpp
class Solution {
public:
    vector<int> maxDepthAfterSplit(string seq) {
        int depth = 0, answer = 0;
        vector<int> out;

        for (auto&c:seq) {
           if (c == '(') {
                depth++;
                out.push_back(depth % 2);
            } else {
                out.push_back(depth % 2);
                depth--;
            }
        }
        return out;
    }
};
```

=== Go
```go
func maxDepthAfterSplit(seq string) []int {
    depth := 0
    out := []int{} // 1. Initialize an empty slice
    for _, value := range seq {
        if value == '(' {
            depth++
            out = append(out, depth%2)
        } else {
            out = append(out, depth%2)
            depth--
        }
    }
    return out
}
```

=== Java
```java
class Solution {
    public int[] maxDepthAfterSplit(String seq) {
        int depth = 0;
        int[] out = new int[seq.length()];  // Preallocate array
        for (int i=0;i<seq.length();i++) {
            if (seq.charAt(i) == '(') {
                depth++;
                out[i] = depth%2;
            }
            else {
                out[i] = depth%2;
                depth--;
            }
        }
        return out;
    }
}
```
