:toc:
:toclevels: 6

=== link:https://leetcode.com/problems/group-the-people-given-the-group-size-they-belong-to/[Group the People Given the Group Size They Belong To]
There are n people that are split into some unknown number of groups. Each person is labeled with a unique ID from 0 to n - 1.

You are given an integer array groupSizes, where groupSizes[i] is the size of the group that person i is in. For example, if groupSizes[1] = 3, then person 1 must be in a group of size 3.

Return a list of groups such that each person i is in a group of size groupSizes[i].

Each person should appear in exactly one group, and every person must be in a group. If there are multiple answers, return any of them. It is guaranteed that there will be at least one valid solution for the given input.
```c
Example 1:
Input: groupSizes = [3,3,3,3,3,1,3]
Output: [[5],[0,1,2],[3,4,6]]
Explanation: 
The first group is [5]. The size is 1, and groupSizes[5] = 1.
The second group is [0,1,2]. The size is 3, and groupSizes[0] = groupSizes[1] = groupSizes[2] = 3.
The third group is [3,4,6]. The size is 3, and groupSizes[3] = groupSizes[4] = groupSizes[6] = 3.
Other possible solutions are [[2,1,6],[5],[0,4,3]] and [[5],[0,6,2],[4,3,1]].
```

=== Approach-1. Hashmap
==== Logic
1. Create a hashmap where key=groupsize, values=vector<of all people in group>
```c
input = [2,1,3,3,3,2,3,3,3, 2, 2]
         0 1 2 3 4 5 6 7 8  9 10
  // key      values
  //  1       {1}
  //  2       {0,5,9,10}
  //  3       {2,3,4,6,7,8}
```
2. Iterte Hashmap.
```
if key == values.size()
  insert value in out
else
  Break values vector into vectors of size=key and insert each into out
```

==== Complexity
1. *Time:* O(n). O(n)=Creating Hashmap. O(n)=Traverse hashmap and create vector
2. *Space:* O(n)

==== Code
===== CPP
```cpp
class Solution {
public:
    vector<vector<int>> groupThePeople(vector<int>& groupSizes) {
        //key=groupsize, value=persons
        unordered_map<int, vector<int>> um;

        // Create hashmap
        // input = [2,1,3,3,3,2]
        // key      value
        //  1       {1}
        //  2       {0,5}
        //  3       {2,3,4}
        int index = 0;
        std::for_each(groupSizes.begin(), groupSizes.end(), [&](int group_size){
            auto it = um.find(group_size);
            if (it != um.end())
                it->second.push_back(index);
            else
                um[groupSizes[index]] = {index};
            index++;
        });
        // for (int i=0;i<groupSizes.size();i++) {
        //     auto it = um.find(groupSizes[i]);
        //     if (it != um.end())
        //         it->second.push_back(i);
        //     else
        //         um[groupSizes[i]] = {i};
        // }

       // Create output from hashmap
       // if values.size() == key
       //   insert directly into output
       // else
       //   Create vectors of size=key and insert each vector into output
        vector<vector<int>> out;
        for (auto&i:um) {
            vector<int> temp;
            int key = i.first;
            vector<int> values = i.second;
            if (key == values.size())
                out.push_back(values);
            else {
                int i=0;
                // split into group of sizes=key
                while (values.size()) {
                    temp.push_back(values.back());
                    values.pop_back();
                    i++;
                    if (i==key) {
                        out.push_back(temp);
                        temp.clear();
                        i=0;
                    }
                }
            }
        }
        return out;
    }
};
```

===== Python
```py
class Solution:
    def groupThePeople(self, groupSizes: List[int]) -> List[List[int]]:
        # key=groupsize, value = vector<indexes having groupSizes>
        um = {}
        out = []
		
        for index, group_size in enumerate(groupSizes):
            if group_size in um:
                # if key=group_size is present in hashmap
                # insert index(ie value) into map
                um[group_size].append(index)
            else:
                # if key is not prsent. 
                # Create key, value pair. Value=List[indexes]
                um[group_size] = [index]
				
        for key, values in um.items():
            temp = []
            if key == len(values):
                out.append(values)
            else:
                i = 0
                # split into groups of size = key
                while values:
                    temp.append(values.pop())
                    i += 1
                    if i == key:
                        out.append(temp)
                        temp = []
                        i = 0

        return out
```
