:toc:
:toclevels: 6

== Requirements
=== Functional
1. Seller can Add/Update products to system: Name, Price, images, delivery time, information, category
2. User can create his profile
3. Service should Render home Screen at user login
4. User can Search keyword(product), with/without filters

=== Non-Functional
1. Scalable. On Flash Sale days, should withstand load
2. Reliable. After user pays, system should provide Ack
3. Secure. As payment is involved
4. Fast

=== Extended
1. Logs generation for debugging
2. Good auth mechanism
  
== API Design (as per Requirement)
link:/Networking/OSI-Layers/Layer-7/Protocols/HTTP/README.adoc[http methods]

[[addUpdateProduct]]
addUpdateProduct (bool new_product, product_id, name, description, images_url, video_url)
```c
PUT https://<server-hostname>:port/v1/update/addUpdateProduct ? new_product=true & product_id=<> & name=<> & description=<> &
```

[[userCreateProfile]]
userCreateProfile (user_name, age, address, phone_no, country, pin_code, longitude, lattitude)
```c
POST https://<server-hostname>:port/v1/create/userCreateProfile ? user_name=name & age=<> & phone_no=<> & country=<> &
```

[[renderHomeScreen]]
renderHomeScreen (user_id, auth_cookie, longitude, lattitude)
```c
POST https://<server-hostname>:port/v1/request/homeScreen ? user_id=<> & auth_cookie=<> & longitude=<> &
```

[[searchProduct]]
searchProduct (user_id, product_name, product_id(optional), filters(optional))
```c
POST https://<server-hostname>:port/v1/request/homeScreen ? user_id=<> & product_name=<> & product_id=<> & filters=<>
```

== BOE Calculations
=== QPS(Queries/Sec)
* *Ask Interviewer: DAU?* 100M
```c
100M/86400 = 1000 req/sec
```

=== BW Estimates. (bytes coming into system/sec)
1000 req/sec. Each req = 10KB. 10k x 1000 = 10MB/sec

=== Storage Estimates 
What we will store?

* Purchase history: (1 item=1MB)
** 1 user buys 1 product in 10 days. Month=3. Year=36. 1MBx100Mx36x5 = 20GB
* Product Listing: (1 Listing = Description+Images+Video = 100MB)
** *Ask Interviewer: How many products?* 100M
** 100M x 100MB x 365 x 5 = 10TB x 1500 = 10PB (Peta byte)
* Product Reviews = (1 review = Text+Image+Video = 10MB)
** *Ask Interviewer: How many product have reviews?* 10%=10M. On average 100 reviews. Total Reviews= 1Billion. 10MBx1B = 10TB
```c
20GB + 10PB + 10TB =~ 10PB
```

== DB Schema (List all objects?)
=== Entities
users, products, reviews, sellers, questions, answers, wishlists

=== Relationship in entities
```c
      |------* wishlists
user 1 ----- * products

                        
product 1 ----- * reviews 1  ----- * responses
         |------ * images

seller 1 ----- * products
question 1 ---- * answers
```

=== Actual Tables
* User table(user_id(primary key), name, email, activation_timestamp, country, age, wishlists, +++<del>+++ Array<addresses> +++</del>+++(use seperate address table for scalabilty))
* User_Addresses table(address_id(pk), user_id(fk))
* Products table(product_id(primary key), description_txt, seller_id(fk), +++<del>+++ Array<images_url>, Array<video_urls>+++</del>+++(use seperate media table for scalabilty))
* Product Media table(id, product_id(fk), image_url/video_url, caption, description)
* Seller table (seller_id, name, address, email, phone, pan, gst_no)
* Review table(review_id, product_id(fk), review_description, +++<del>+++ Array<image_url>, Array<video_url> +++</del>+++ (Will go in review media table), user_id(fk))
* Review Media Table (similar to product media table)
* Wishlist (id, user_id(fk), number_of_items, Array<product_id>, name, created_date)
* Question (id, product_id(fk), description, user_id_who_raised_question(fk))
* Answer (id, question_id(fk), description, user_id_who_answered(fk))
