:toc:
:toclevels: 5

== link:https://leetcode.com/problems/find-players-with-zero-or-one-losses/[2225. Find Players With Zero or One Losses]
You are given an integer array matches where matches[i] = [winneri, loseri] indicates that the player winneri defeated player loseri in a match.

Return a list answer of size 2 where:

answer[0] is a list of all players that have not lost any matches.
answer[1] is a list of all players that have lost exactly one match.
The values in the two lists should be returned in increasing order.

Note:

You should only consider the players that have played at least one match.
The testcases will be generated such that no two matches will have the same outcome.
 
```
Example 1:
Input: matches = [[1,3],[2,3],[3,6],[5,6],[5,7],[4,5],[4,8],[4,9],[10,4],[10,9]]
Output: [[1,2,10],[4,5,7,8]]
Explanation:
Players 1, 2, and 10 have not lost any matches.
Players 4, 5, 7, and 8 each have lost one match.
Players 3, 6, and 9 each have lost two matches.
Thus, answer[0] = [1,2,10] and answer[1] = [4,5,7,8].

Example 2:
Input: matches = [[2,3],[1,3],[5,4],[6,4]]
Output: [[1,2,5,6],[]]
Explanation:
Players 1, 2, 5, and 6 have not lost any matches.
Players 3 and 4 each have lost two matches.
Thus, answer[0] = [1,2,5,6] and answer[1] = [].
```

== Approach. Search winnner in loosers
=== Logic
* Create list of winners, loosers.
* Iterate through winners array and search winner in loosers, if winner is not found in loosers array, he's a winner, insert in min_heap.
* iterate through loosers and find looser who lost only 1 time, insert in another min_heap
* Iterate through both min_heaps and create output 2D Array.

=== Complexity
* Time: O(n)+O(nlogn) = O(nlogn). O(nlogn) for balancing of BBT(priority queue)
* Space: O(2n)

=== Code
==== CPP
```cpp
class Solution {
public:
    vector<vector<int>> findWinners(vector<vector<int>>& matches) {
        unordered_set<int> winners;
        unordered_map<int, int> loosers;
        // Create seperate winners, loosers list. Count number of losses.
        for (auto i:matches) {
            winners.insert(i[0]);
            loosers[i[1]]++;
        }
        priority_queue<int, vector<int>, greater<int>> winner_list; 
        priority_queue<int, vector<int>, greater<int>> looser_list;
        // Check winner in looser
        // if not found, this winner would go into output array. insert into priority_queue
        for (auto&i:winners) {
            if (loosers.find(i) == loosers.end())
                winner_list.push(i);
        }
        // Find looser which have lost only 1 match
        // this looser would go into output array. insert into priority_queue
        for (auto& [key,value]:loosers) {
            if (value == 1)
                looser_list.push(key);
        }
        // Create output vector in winner_list, looser_list
        vector<vector<int>> out;
        vector<int> temp;
        while (!winner_list.empty()) {
            temp.push_back(winner_list.top());
            winner_list.pop();
        }
        out.push_back(temp);
        temp.clear();
        while (!looser_list.empty()) {
            temp.push_back(looser_list.top());
            looser_list.pop();
        }
        out.push_back(temp);
        return out;
    }
};
```
