:toc:
:toclevels: 5

== link:https://leetcode.com/problems/kth-largest-element-in-an-array/description/[215. kth largest element in array]
```c
Input: [3,2,1,5,6,4] and k = 2
Output: 5

Input: [3,2,3,1,2,4,5,5,6] and k = 4
Output: 4 
```

=== Approach-1. Sort. O(nlogn)
==== Complexity
* Time: O(nlogn)
* Space: O(1)

==== Code
```cpp
int findKthLargest(vector<int>& nums, int k) {
  sort (nums.begin(),nums.end());
  return nums[nums.size()-k];
}   
```

=== Approach-2. Min-Heap. O(nlogn)
==== Logic
* 1. Take min_heap of size=k. 
* 2. min_heap will contain k elements, min at top.
* 3. Kth largest element will be = top of min heap.
==== Complexity
* Time: [Rebalancing Min heap O(nlogn)]()
* Space: O(n)

==== Code
```cpp
class Solution {
public:
    int findKthLargest(vector<int>& nums, int k) {
        // Take min_heap of size k
        priority_queue<int, vector<int>, greater<int>> minheap;
        for (auto&i:nums) {
            if (minheap.size() < k)
                minheap.push(i);
            else {
                if (i > minheap.top()) {
                    minheap.pop();
                    minheap.push(i);
                }
            }
        }
        return minheap.top();
    }
};
```

=== Approach-3 / Quick-Select. O(n)
==== Quick-Select
* Quick select Algo works same as link:/DS_Questions/Sorting[Quick Sort]
```c
Input = {7, 10, 4, 3, 20, 15}, k = 3
3rd=k largest element = 10        //20,15,10
3rd=k largest element = (n - k + 1) smallest element
  n = 6, k = 3, n-k+1 = 4
  4th smallest element = 10     //3,4,7,10

Input = {7, 10, 4, 3, 20, 15}, k = 4
4th largest = 3rd smallest = 7      //3,4,7,10,15,20
```
* We will find k smallest element.
** Quick Select is similar to QuickSort. The difference is, instead of recurring for both sides(after finding pivot), it recurs only for the part that contains the kth smallest element, This reduces the expected complexity from O(n log n) to O(n).

==== Logic
```c
{7, 10, 4, 3, 20, 15}, k = 3          //Step-1. Choose pivot same as Quick sort
 |
 pivot

  if (index_of_partitioned > k)
    recur in left
  else if (index_of_partitioned < k)
    recur in right
  else
    Found kth smallest element
    return
```
==== Complexity
* _1. Time:_ Good, Average case:O(n). Worst case: O(n^2^). link:/DS_Questions/Sorting[What is worst case of Quick sort]
** _Guranteed O(n)_: Whenever we get worst case input, just shuffle the input. Done in code below. //Blum-Floyd-Pratt-Rivest-Tarjan algorithm
* _Space:_ O(1). No extra space

==== Code
===== CPP
```cpp
class Solution {
using vec = vector<int>;   

//Standard partition process of QuickSort(). It considers the last element as pivot
//and moves all smaller element to left of it and greater elements to right
int partition(vec& arr, int left, int right) {
    int pivot = arr[right];    //OR pivot = arr[left + (right-left)/2];
    int i = left;
    for (int j = left; j <= right - 1; j++) {
        if (arr[j] <= pivot) {
            swap(arr[i], arr[j]);
            i++;
        }
    }
    swap(arr[i], arr[right]);
    return i;
}

//arr, left, right, k
int kthSmallest(vec& arr, int left, int right, int k) {

    // If k is smaller than number of elements in array
    if (k > 0 && k <= right - left + 1) {

        // Partition the array around last element and get position of pivot element in sorted array
        int index = partition(arr, left, right);

        // If position is same as k
        if (index - left == k - 1)
            return arr[index];

        // If position is more, recur for left subarray
        if (index - left > k - 1)
            return kthSmallest(arr, left, index - 1, k);

        // Else recur for right subarray
        return kthSmallest(arr, index + 1, right,
                            k - index + left - 1);
    }

    // If k is more than number of elements in array
    return INT_MAX;
}    
public:
    int findKthLargest(vector<int>& a, int k) {
      //4,3,7,10,15,20. 3rd Largest = 4th smallest = 10
      //3rd largest = n - 3 + 1 smallest
      //            = 6 - 3 + 1 = 4th smallest
      
      //Guranteed O(n)
      //Randomize the input, so that even when the worst case input would be provided the algorithm wouldn't be affected.
      //So all what it is needed to be done is to shuffle input.
      auto rng = std::default_random_engine {};
      std::shuffle(std::begin(a), std::end(a), rng); 
        
      return  kthSmallest(a, 0, a.size() - 1, a.size()-k+1);
    }
};

int main() {
    vector<int> a = {7, 10, 4, 3, 20, 15};
    cout << findKthLargest (a, 3);    //10
}
```
