:toc:
:toclevels: 6

== link:https://leetcode.com/problems/sliding-window-maximum/description/[239. Sliding Window Maximum]
* You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position.
* Return the max sliding window.
```c
Example 1:
Input: nums = [1,3,-1,-3,5,3,6,7], k = 3
Output: [3,3,5,5,6,7]
Explanation: 

Window position                Max
[1  3  -1] -3  5  3  6  7       3
 1 [3  -1  -3] 5  3  6  7       3
 1  3 [-1  -3  5] 3  6  7       5
 1  3  -1 [-3  5  3] 6  7       5
 1  3  -1  -3 [5  3  6] 7       6
 1  3  -1  -3  5 [3  6  7]      7
```
  
== Approach-1. Maintain window in multiset<int>
=== Logic
* 1. Keep window inside `multiset<int>`. multiset can have duplicate elements and stores elements in sorted order.
```c
 multiset<int>              will store {1,3,5,6,7}
 multiset<int, greter<int>> will store {7,6,5,3,1}
```
* 2. When number of elements becomes greater than k, Search 1st element 
```c
 1 3 -1 -3 5 3 6 7    multiset
 |    |                {3,1-1}

1 3 -1 -3 5 3 6 7      {3,-1,-3}  //Search 1 and remove from multiset
  |     |
```

=== Complexity
* *Time:*
** `set<int>` search,rebalance = nlog(n). Since window size=k. klog(k). n=number of elements. nklog(k)
* *Space:* k. Window size

=== Code
==== CPP
```cpp
class Solution {
public:
    vector<int> maxSlidingWindow(vector<int>& nums, int k) {
        // set<> stores values in sorted order using BBT. Complexity nlog(n)
        // Keep windows in set
        multiset<int, greater<int>> msWindow;
        vector<int> out;
        if (k==0)
            return out;

        for (int i =0; i<nums.size(); ++i) {
            // keep inserting element into window=set
            msWindow.insert (nums[i]);

            // When window size == k
            // Get Max element from current window = first element. Since set is sorted
            // Remove 1st element of window of array.
            if (msWindow.size() == k) {
                out.push_back (*msWindow.begin());
                msWindow.erase (msWindow.find(nums[i+1-k]));
            }
        }
        return out;
    }
};
```


== Approach-2. Deque
- maintain a deque of size=window size. Insert at back. Remove from front
- if element incoming vector > front of deque. remove all elements smaller than current element

=== Code
```cpp
class Solution {
public:
    vector<int> maxSlidingWindow(vector<int>& nums, int k) {
        deque<pair<int, int>> dq;  // {value, index}
        vector<int> result;

        for (int i = 0; i < nums.size(); i++) {

            // 1. Remove elements outside the current window
            if (!dq.empty() && dq.front().second <= i - k) {
                dq.pop_front();
            }

            // Remove all elements from dq front till present element's value greater than element in deque
            while (!dq.empty() && dq.back().first <= nums[i]) {
                dq.pop_back();
            }

            // 3. Add current {value, index}
            dq.push_back({nums[i], i});
            
            /*for (auto&i:dq) {
                cout << i.first << ", " << i.second << "|";
            }
            cout << "\n";*/

            // 4. Once window reaches size k, front has maximum
            if (i >= k - 1) {
                result.push_back(dq.front().first);
            }
        }

        return result;
    }
};
```
