:toc:
:toclevels: 6

== link:https://leetcode.com/problems/divide-array-into-arrays-with-max-difference[2966. Divide Array Into Arrays With Max Difference]
you are given an integer array nums of size n and a positive integer k.

Divide the array into one or more arrays of size 3 satisfying the following conditions:

Each element of nums should be in exactly one array.
The difference between any two elements in one array is less than or equal to k.
Return a 2D array containing all the arrays. If it is impossible to satisfy the conditions, return an empty array. And if there are multiple answers, return any of them.

```c
Example 1:
Input: nums = [1,3,4,8,7,9,3,5,1], k = 2
Output: [[1,1,3],[3,4,5],[7,8,9]]
Explanation: We can divide the array into the following arrays: [1,1,3], [3,4,5] and [7,8,9].
The difference between any two elements in each array is less than or equal to 2.
Note that the order of elements is not important.

Example 2:
Input: nums = [1,3,3,2,7,3], k = 3
Output: []
Explanation: It is not possible to divide the array satisfying all the conditions.
```

== Approach-1. sort. Divide into group of 3
=== Logic
* if does not have elements in multiple of 3. return
* Sort the input array
* Take 3 elements at a time {ele1, ele2, ele3}
** if ele3-ele1 <= k //means diff is smaller than k
** Take these 3 elements and put in output vector

=== Complexity
* Time: O(nlogn)
* Space: O(1)

=== Code
==== CPP
```cpp
class Solution {
public:
    vector<vector<int>> divideArray(vector<int>& nums, int k) {
        // 1. if does not have elements in multiple of 3 return
        int size = nums.size();
        if (size % 3 != 0)
            return {};

        // 2. Sort the input array
        sort(nums.begin(), nums.end());

        // 3. Take 3 elements at a time {ele1, ele2, ele3}
        // if ele3-ele1 <= k //means diff is smaller than k
        // Take these 3 elements and put in output vector
        vector<vector<int>> out(size / 3, vector<int>(3));
        int groupIndex = 0;
        for (int i = 0; i < size; i += 3) {
            if (i + 2 < size && nums[i + 2] - nums[i] <= k) {
                out[groupIndex] = { nums[i], nums[i + 1], nums[i + 2] };
                groupIndex++;
            }
            else {
                return {};
            }
        }
        return out;
    }
};
```
==== Rust
```rs
impl Solution {
    pub fn divide_array(nums: Vec<i32>, k: i32) -> Vec<Vec<i32>> {
        // 1. if it does not have elements in multiple of 3, return
        let size = nums.len();
        if size % 3 != 0 {
            return Vec::new();
        }

        // 2. Sort the input array
        let mut sorted_nums = nums.clone();
        sorted_nums.sort();

        // 3. Take 3 elements at a time {ele1, ele2, ele3}
        // if ele3 - ele1 <= k //means diff is smaller than k
        // Take these 3 elements and put in the output vector
        let mut out = Vec::with_capacity(size / 3);
        let mut group_index = 0;
        for i in (0..size).step_by(3) {
            if i + 2 < size && sorted_nums[i + 2] - sorted_nums[i] <= k {
                out.push(vec![sorted_nums[i], sorted_nums[i + 1], sorted_nums[i + 2]]);
                group_index += 1;
            } else {
                return Vec::new();
            }
        }

        out
    }
}
```
