:toc:
:toclevels: 6

=== What
* JIMS is a Windows Application installed on windows machine near AD.
** It fetch user information(device,username,groups) from AD, creates a report & provides to SRX or vSRX device.
** It can Supports upto 250 Domain Controllers, 250k users, 100 SRX devices.
```mermaid
sequenceDiagram
  participant o as syslog server<br><br>VPN G/w<br><br>Captive Portal
  participant u as user
  box customer premises
  participant ad as AD
  participant col as JIMS Collector
  participant ser as JIMS-server
  participant sled as SLED
  participant srx as SRX
  end

  box Cloud
  participant srv as JIMS-server
  participant vsrx as JVSRXMS
  end

 rect rgb(224, 224, 224) 
 par READ USERS,GROUPS
 col ->> ad: ldapquery<br>Read users to <br>group mapping
 ad -->> col: group1(user1,user4)<br>group2(user5,user8)
 col ->> ser: user1: group1(user1,user4)<br>group2(user5,user8)
 ser ->> sled: user1: group1(user1,user4)<br>group2(user5,user8)
 Note over sled: Store mapping
 end end


 Note over u: Login to domain
 Note over u: No internet<br>Check cached credentials
 u ->> ad: if internet present<br>(user/pass)
 Note over ad: Event log<br>login<br>user1(1.2.3.4)
 col ->> ad: ReadEventLogs()
 ad -->> col: login/logout<br>user1(1.2.3.4)
 col ->> ser: login<br>user1(1.2.3.4)(group1)
 o ->> col: login/logout events
 ser ->> sled: login/logout<br>user1(1.2.3.4)
 Note over sled: user:1.2.3.4

 rect rgb(191, 223, 255)
 par GET OAUTH TOKEN
 Note over srx: Admin configure<br>jims user/pass
 srx ->> ser: HTTP GET token<br> user/pass
 Note over ser: Veify user/pass
 ser ->> srx: oauth token (expire 8hours)
 end
 end

 rect rgb(255, 255, 153)
 Note over srx: Need info of<br>IP=4.5.6.7
 srx ->> ser: IP query(4.5.6.7)
 ser -->> srx: login<br>user1(4.5.6.7)(group1)
 end

 rect rgb(255, 204, 204)
 par BATCH QUERY
 srx ->> srx: Every 5 sec
 srx ->> ser: Batch Query
 ser -->> srx: login<br>user1(4.5.6.7)(group1)
 end
 end
```

=== JIMS b/w AD and SRX
1. JIMS collects users,groups, event logs from Active Directory. From link:/Operating_Systems/Windows/Active_Directory/Computer_Object[Event logs] JIMS determines the IP-addresses(devices) associated with users.
2. On IP,Batch query JIMS provides report(IP address(device),username,groups). SRX creates policies to enforce user-based and group-based security policy control over access to protected corporate resources and the Internet.

=== Queries to JIMS
==== IP Query
Provide user information from IP Address of user's device.
```c
                  JIMS                                          SRX_Device
                    <-- Give user info (IP=x.y.z.g)/HTTP_HTTPS---
```
==== batch query
Get information for group of users.
