:toc:
:toclevels: 6

=== What
* JIMS is a Windows Application installed on windows machine near AD.
** It fetch user information(device,username,groups) from AD, creates a report & provides to SRX or vSRX device.
** It can Supports upto 250 Domain Controllers, 250k users, 100 SRX devices.
```mermaid
sequenceDiagram
  participant o as syslog server<br><br>VPN G/w<br><br>Captive Portal
  participant u as user
  box customer premises
  participant ad as AD
  participant col as JIMS Collector
  participant ser as JIMS-server
  participant sled as SLED
  participant srx as SRX
  end

  box Cloud
  participant srv as JIMS-server
  participant vsrx as JVSRXMS
  end

 rect rgb(224, 224, 224) 
 par READ USERS,GROUPS
 col ->> ad: ldapquery<br>Read users to <br>group mapping
 ad -->> col: group1(user1,user4)<br>group2(user5,user8)
 col ->> ser: user1: group1(user1,user4)<br>group2(user5,user8)
 ser ->> sled: user1: group1(user1,user4)<br>group2(user5,user8)
 Note over sled: Store mapping
 end end


 Note over u: Login to domain
 Note over u: No internet<br>Check cached credentials
 u ->> ad: if internet present<br>(user/pass)
 Note over ad: Event log<br>login<br>user1(1.2.3.4)
 col ->> ad: ReadEventLogs()
 ad -->> col: login/logout<br>user1(1.2.3.4)
 col ->> ser: login<br>user1(1.2.3.4)(group1)
 o ->> col: login/logout events
 ser ->> sled: login/logout<br>user1(1.2.3.4)
 Note over sled: user:1.2.3.4

 rect rgb(191, 223, 255)
 par GET OAUTH TOKEN
 Note over srx: Admin configure<br>jims user/pass
 srx ->> ser: HTTP GET token<br> user/pass
 Note over ser: Veify user/pass
 ser ->> srx: oauth token (expire 8hours)
 end
 end

 rect rgb(255, 255, 153)
 Note over srx: Need info of<br>IP=4.5.6.7
 srx ->> ser: IP query(4.5.6.7)
 ser -->> srx: login<br>user1(4.5.6.7)(group1)
 end

 rect rgb(255, 204, 204)
 par BATCH QUERY
 srx ->> srx: Every 5 sec
 srx ->> ser: Batch Query
 ser -->> srx: login<br>user1(4.5.6.7)(group1)
 end
 end
```

=== JIMS b/w AD and SRX
- _1._ JIMS communicates with Microsoft Domain Controllers or  in AD(Active Directory) domains & collect event log information. 
  - Using the event log information, JIMS determines the IP-addresses(devices) associated with users, stores in cache.
- _2._ JIMS gets group information from AD. ie groups to which user belongs, stored in cache.
- _3._ With IP address(device),username, and group relationship information, JIMS generates a report and sends it to the SRX Series devices. if CSO is present report is sent to that as well.
- _4._ Each SRX Series device receives the report(IP address(device),username,user group relationship information) and generates authentication entries that are used to enforce user-based and group-based security policy control over access to protected corporate resources and the Internet.
<img src=JIMS_SRX.JPG width=700/>
<img src=JIMS.jpg width=700/>

=== Queries to JIMS
==== IP Query
This is a feature to be enabled on SRX device. SRX will send query message(over HTTP/HTTPS) to JIMS to get user information based on IP Address of user's device.
```c
                  JIMS                                          SRX_Device (IP Query enabled)
                    <-- Give user info (IP=x.y.z.g)/HTTP_HTTPS---
                    
/////////SRX///////////
user@host# set services user-identification device-information authentication-source network-access-controller option-1
option-1
  no-ip-query	: Disable IP query. IP query is enabled by default.
  query-delay-time : Time after which the SRX Series device sends the query. Rather than allow the SRX Series device to respond automatically by sending a user query immediately, you can set a query-delay-time parameter, specified in seconds, that allows the SRX Series device to wait for a period of time before sending the query. Default: 15. Range: 0-60 seconds
```
==== batch query
Get information for group of users.
