:toc:
:toclevels: 6

== AD = Directory storing users,groups
Active Directory(AD) is a directory service for Windows. Directory service stores users,groups,computers,services

== Alias / Domain Alias
- It means 2 names of 1 domain. For example: atest.com is 1 domain. Now atest-alias.com also points to same domain. Users can login as:
```c
amit@atest.com OR
amit@atest-alias.com
```
=== How to Add Domain Alias
* *1. Add UPN Suffix*
** link:https://www.stephenwagner.com/2018/10/16/how-to-add-an-alternative-upn-suffix-to-an-active-directory-domain/[Doc1]
** link:https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization?view=o365-worldwide[Microsoft Doc]
** We will add different UPN suffixes (aliases) for users.
** Add upn Suffix = atest-alias.com. Then go into the properties of user2 and change the UPN suffix to the newly-added atest-alias.com.  With that change applied, the user should then be able to sign in as user@atest-alias.com at the main Windows login screen.
** “Active Directory Domains and Trusts” > Properties > Type in your new domain suffix in to the “Alternative UPN suffixes” > Add > Apply
** Open User Properties > Account tab > UPN suffix drop-down list > choose the new UPN suffix

== cn = common name
user object in ldap

== DC = Domain Controller
- Domain Controller(DC) serves the directory maintained by [AD](#ad).
- Events are recieved from DC. Users/Groups from AD

== dc = domain component
This is designator of AD DNS namespace. For example for windows-2012.gsslab.pnq.redhat.com it would be dc=gsslab,dc=pnq,dc=redhat,dc=com

== dn = Distinguished name
Collection of RDN forming complete URL of resource. This is object's entire path to the root of the LDAP namespace. Example: DN of amitk is:  CN=root,CN=Users,DC=gsslab,DC=pnq,DC=redhat,DC=com

=== baseDN/base DN
baseDN of a search is the starting point. Where it will start searching. it can be way below root of tree.

=== bindDN/ bind DN
In LDAP tree, bind dn/ binddn is username/object to which you will bind and get permissions to do whatever you're trying to do. Typically admin.

== DNS Suffix / Domain Name System suffix
This is a domain name that is appended to the end of a hostname to create a fully qualified domain name (FQDN)

== rdn = Relative Distinguished Name
This is Single AV(Attribute value Pair). Eg: DC=Domain Component, CN=Common Name, OU=Orgnizational Unit, S=Street, L=locality, ST=state, C=country, UID=user ID

== Group Policy
- Admin can apply policies on users, computers. 

== link:https://docs.microsoft.com/en-us/windows/win32/ad/naming-contexts-and-partitions[Naming Context / Directory Partition]
- AD is partitioned and information is logically stored in partitions. We cannot store whole under 1 head.
- AD contains following partitions:
|===
|Name|Contains

|1. Configurtion Naming Context (CN=Partitions,CN=Configuration,DC=test,DC=com)|Replication Topology, other data to be replicated in forest
|2. Schema Partition|
|3. Domain Partition|
|===

== link:https://docs.microsoft.com/en-us/windows/win32/adschema/a-ncname[nCName]
This is dn of Naming Context in AD.

== rootDN
- Administrator of Directory Server. Eg: "cn=Manager,dc=gsslab,dc=pnq,dc=redhat,dc=com"

== rootDSE
- This is NULL DN entry, provides information about AD Capabilities & Content. 
- Entries are: 
  - _1. namingContexts:_ Base DNs of tree containing data that client generally intended to interact with.
  - _2. SubSchemaSubEntry:_ Location of Primary schema of Directory Server.     
  - _3.SupportedLDAPVersion_    
  - _4.supportedControl:_ OIDs of all request controls that server is willing to accept.

== samAccountName
=== User
- Logon Name in Pre-Windows 2000. SamAccountName must be unique among all security principal objects within the domain. Logon name format is : DomainName\testUser

=== Computer/Device/Machine Object
- sAMAccountName attribute of a [computer object](/Operating_Systems/Windows/Active_Directory/Computer_Object) is the NetBIOS name of the computer with a trailing dollar sign, `$`, appended. AD maintains index in database on sAMAccountName
- **why $ at end?**
  - Machine accounts are always given a trailing dollar sign "$" in their sAMAccountName attribute; this causes them to not be enumerated by certain APIs
  - Computer account and user account can have same names & to identify computer account this is used.

== Search Filter
Search filters enable to define search criteria and provide more efficient searches.
```c
"(objectClass=*)" 	                                          All objects.
"(&(objectCategory=person)(objectClass=user)(!(cn=andy)))" 	  All user objects but "andy".
"(sn=sm*)" 	                                                  All objects with a surname that starts with "sm".
"(&(objectCategory=person)(objectClass=contact)(|(sn=Smith)(sn=Johnson)))" 	All contacts with a surname equal to "Smith" or "Johnson".
```

== UPN / Universal Principal Name
User amit under test.local then UPN would be amit@test.local 

=== UPN Suffix / upnSuffix
```c
  amit@test.local
  UPN  |-suffix-|
```

=== UPN Suffix Alias or Suffix Alias
* Instead of amit@test.local we can use custom suffix eg: amit@test.focal 
* Why we need upn suffixes alias? We donot want to expose `test.local` externally we want to expose hence we expose `test.focal`
```c
  amit@test.local    =    amit@test.focal
```
* It means user has multiple domain names, he can login with any of them.
