:toc:
:toclevels: 6


== const
=== const Member Variables
==== 1. const member variables can be initialized only once
java does not have const keyword, rather it has final.
```cpp
        const int a = 2;
        a=4;                 //Compilation Error
```

=== const Member Function
==== 1. Can only change mutable variables 
int const fun(), const int fun()//Both are same function returning constant Integer
```cpp
        int a;    mutable int c;
        void fun() const{
            a = 5;        //Compilation Error
            c = 2;        //OK
        }
```

=== const Function Arguments
==== 1. Cannot be modified
```cpp
        int fun(const int a){
            a=10;    //Compilation Error
        } 
```

=== const Objects
==== 1. Member variables present in cosnt object cannot be changed
```cpp
        const obj s(1,2);
        obj.a=100;    //Compilation Error
```

==== 2. const object can only call const function
```cpp
class A {
public:
	void fun() { cout << "fun"; }
};

int main() {
	const A obj;
	obj.fun();
}
$ ./a.out
Compilation Error				//Can be resolved either by making fun() const. or making obj non-const.
```

== explicit
=== Implicit conversion / Conversion Constructor
* Compiler converts data-type to class object which is wrong. This is allowed for contructor taking 1 argument.
* Example-1: fun() takes object as argument but we passed int and compiler did conversion internally. This is done using default constructor(1).
```cpp
class A {
  int a;
public:
    A(int b) : a(b) {}             //Conversion ctr
    int get() {
      return a;
    }
};

int main() {
  A obj1 (3);
  cout << obj1.get();			//3
  obj1 = 4;				//Implicit Conversion
  cout << obj1.get();			//4
}
```

**Explicit** Explicit can only come in front of 1 argument constructor. Prefixing the explicit keyword before constructor prevents the compiler for using that constructor for implicit conversions. Above code will give error, we need.
```c++
class A {
  ...
  public:
     explicit A(int b) : a(b) {}             //CONSTRUCTOR PREFIXED with EXPLICIT stops implicit conversion
  ...
};
```

== extern
=== extern C
* With extern C we tell C++ Compiler not to [mangle name](/Languages/Programming_Languages/c++/#nm) of functions/symbols.
* "extern C" is used to call C functions from C++ code.

* *Problem: Compile C code with g++ compiler?*
** fun() is present in C code. fun() will be used by C++ code by shared library(`*.so`) which will be dynamically linked.
** C++ Compiler will [mangle function name](/Languages/Programming_Languages/c++/#nm) from fun() to f12asfn() at time of object code creation.
** At time of Linking, C++ code calls f12asfn() but shared-library will call the function by actual name, and actual name is mangled by compiler it will generate a linker error.
```c
int printf(const char *format,...);
int main(){
    int a = 1;
    printf("%d",a);
}
$ g++ test.cpp
$ ./a.out
undefined reference to `printf(char const*, ...)'
```

* *Solution:* Ask compiler not to mangle function name if its coming from C.
```cpp
#ifdef __cplusplus
extern "C" {                //Do not mangle name of foo().
#endif
  int printf(const char *format,...);
#ifdef __cplusplus
}
#endif

int main(){
    int a = 1;
    printf("%d",a);
}
$ ./a.out
1
```

== new keyword
Used for Allocating Objects.
```cpp
ptr = new data_type;

double *ptr = new double; 
char *ptr = new char[20];	     
char *ptr = new char[20](); 	//Initializing Array with 0 values
int* ptr = new int(5);		//Allocates int, Initializes to 5
```

== override
* This keyword indicates, derived class is intended to override a virtual function declared in a base class. 
* This helps improve code clarity and can help catch certain types of errors during compilation
```cpp
class Base {
public:
    virtual void someFunction() {
        // Base class implementation
    }
};
class Derived : public Base {
public:
    void someFunction() override {
        // Derived class implementation
    }
};
```

== scope resolution
=== 1. class members can be accessed using sr
```cpp
class A {
public:
    void set(int x) {A::a = x;}		//“A::a = x” is same as “this->a = x”
    int get() { return a; }	//Bright Computing(Netherland)
private:
    int a;
};

int main() {
    A obj;
    obj.set(4);
    cout << obj.get();
    return 0;
}
```

== static
It has different meaning in different contexts.

=== Static member variables
==== 1. static variable are initialized outside the class
* static variables are shared among all Objects of class. Only 1 copy of variables is created.
* Since we cannot have multiple copies of static variable hence cannot be initialized inside constructor.
* _Initialization:_ at compile-time.
* _Calling:_ Without creation of class object, ie shared among objects.
* Java does not support Static Local variables
```cpp
class A{
  static int var;
public:
  A(){}
  void disp(){
     cout<<var;
  }
};
int A::var=10;  //Rule: Initialize static variable. THIS IS REQUIRED, else Compiler will give undefined reference Error for var
int main(){
	A obj1, obj2;
	obj1.disp();    //10
	obj2.disp();    //10
} 
```

=== Static member Functions
==== 1. Called without class object
SMF can access: Static Data Members, Static Member Function, non-static functions from outside class.
```c++
class A{
public:
  static void fun(){
    cout<<"fun";
  }
};
int main(){
  A::fun();         //fun
}
```

==== 2. static member functions don't have access to this pointer or super
```cpp
class A {
    static int a;
public:
    static A& fun();
};
int A::a = 0;
A& A::fun() {
    A::a++;
    return *this;
}
int main() {
    A obj;
    obj.fun();
}
$ ./a.out
‘this’ is unavailable for static member functions
```

==== 3. static class
Only present in Java. Way of grouping classes in Java. Only Inner(Nested classes) can be created static. But its not necessary that all nested classes needs to be static. 
```java
public class test{
    public static class InnerStatic{
        public InnerStatic(){    System.out.println("InnerTest");    }
    };
    public test(){    System.out.println("test");    }    
};
```

== final
|===
|Final|Java|C++

|Class variable|Should be initialized at time of declaration. Value cannot be changed|same as const
|Class Method|if final function is defined in base class, it cannot be overridden in derv class(Compilation error). Final methods gets inherited|final
|final class|Cannnot be extended/inherited
|===

== this pointer
* This pointer holds address of current active object
* this pointer is stored on stack, heap, DS(based on implementation)
* We know only every object has seperate data members, But All objects have same member functions in Code segment. So How a function knows which object is calling it to set/get the variables => Using this pointer.
* `(*this):` returns address of current object.

```cpp
class A{
  int a;
public:
  void fun(int x){        //Implemented as void fun(const test *this, int x)
    a = x;                //this->a=x
   }
};

int main(){
    A obj
    obj.fun(10);                //obj.fun(&obj, 10);
}
```

== Volatile
* Request to complier to not place variable on Register(ie donot Optimize the variable).
* Optimization:
1. Compiler moves some variables from memory to register to perform fast & deliver speed.
2. Programmer Optimization: Less time,space complexity of written code
```c
int main (){
   int val;   val++;		//val would be copied from Memory to CPU register, then operation is performed.
}
int main (){
   volatile int value;  val++;	//val not copied from Memory to CPU register.
}
```

=== Why volatile?
* 1. volatile variable is not placed on register, making sure variable is not changed outside current scope.
* *Use Case:* 2 Threads are talking on global variable. This variable should not be optimized(ie should be volatile)
** Let Thread-1 does var++, Compiler optimizes the variable & places on Register. Since threads can execute asynchronously, Thread-2 comes in & tries to read. 
** Since on variable some CPU operations are going on, its final value is yet no calculated. Thread-2 reads wrong value.
