:toc:
:toclevels: 6

== link:https://leetcode.com/problems/set-mismatch/description/[645. Set Mismatch]
You have a set of integers s, which originally contains all the numbers from 1 to n. Unfortunately, due to some error, one of the numbers in s got duplicated to another number in the set, which results in repetition of one number and loss of another number.

You are given an integer array nums representing the data status of this set after the error.

Find the number that occurs twice and the number that is missing and return them in the form of an array.

```c
Example 1:
Input: nums = [1,2,2,4]
Output: [2,3]

Example 2:
Input: nums = [1,1]
Output: [1,2]
```

== Approach-1. count using ordered map
=== Logic
* Put all numbers in map and count the frequencies
```
[1,2,2,4]
map ={<1,1>, <2,2>, <4,1>}
```
* iterate through the map and find 2 things:
** Number whose freq is 2(that is repeated number)
** if (next_number - present_number > 2). Then missing_number = present_number+1
```c
repeted_number = 2
missing_number = 3
```

=== Complexity
* Time: O(n). Put all numbers in map and iterate 
* Space: O(n). map

=== Code
==== CPP
```cpp
class Solution {
public:
    vector<int> findErrorNums(vector<int>& nums) {
        std::vector<int> out;
        int repeated_num = 0, missing_num = 0;
        std::map<int, int> mCount;
        for (auto& i : nums) 
            mCount[i]++;
        for (auto it = mCount.begin(); it != std::prev(mCount.end()); it++) {
            auto itn = std::next(it);
            if (it->second == 2)
                repeated_num = it->first;
            if (itn->first - it->first == 2)
                missing_num = it->first + 1;
        }
        auto it = mCount.end();
        --it;
        if (repeated_num == 0)
            repeated_num = it->first;
        if (missing_num == 0) 
            if (it->first != nums.size())
                missing_num = it->first + 1;
            else if (nums[0] != 1)
                missing_num = 1;
        out = {repeated_num, missing_num};
        return out;
    }
};
```
