:toc:
:toclevels: 6

== Collections
go library provides built-in collection types to handle different data structures.

=== Array (fixed size)
* An array in Go is a fixed-size collection of elements of the same type. Once you define the size of an array, it cannot be changed
```go
func main() {
  arr := [6]int{1,2,3,4,5,6}    //[n values] type {}
  var len = len(arr);
}
```

=== channels
- Communication and synchronization between goroutines=Tasks in Rust (concurrently executing functions). They provide a way to send and receive data safely between goroutines.

=== Maps / Dictionary(Python) / unordered_map(C++) / Hash_map(Rust)

==== Sets
Go doesn't have a built-in set data type, but you can simulate sets using maps.

=== Slice [] (Dynamic Array) = C++(vector`<int>`) = link:Languages/Programming_Languages/Rust/Collections[Rust(vec`<i32>`)]
* A slice represents a view of contiguous sequence of elements in memory.
* *Slice contains 3 components*
** _1. Pointer to underlying array:_ A slice holds a reference to the underlying array that stores the elements.
** _2. Length:_ number of elements in slice.
** _3. Capacity:_ maximum number of elements it can hold 
```go
package main
func main() {

// SLICE DECLARATION
  var arr []int                       //Empty vector
  slice := make([]int, 5)             //Slice size=5

// INITIALIZATION
  arr := []int {1,2,3,4,5,6}        //Length=6. number of elements provided
  for i:=0; i<5; i++ {
    slice[i] = 0;
  }
  
// SLICE MODIFICATION: Changing elements of a slice modifies the corresponding elements of its underlying array 
  slc[0] = 899
  fmt.Println(arr[1])             //899

// length: no of elements slice contains
// capacity: no of elements in underlying array
  fmt.Println(len(slc),cap(slc))  //3 5

// NIL SLICE
  var nilSlc[]int
  fmt.Println(len(nilSlc), cap(nilSlc))   //0 0

//RESLICING:  Slice the Slice's length to new length
    slc1 := []int{10,20,30,40,50}
    slc1 = slc1[:0]
    fmt.Println(slc1)                       //[]
    slc1 = slc1[:4]
    fmt.Println(slc1)                       //[10,20,30,40]
    slc1 = slc1[2:]
    fmt.Println(slc1)                       //[30,40]

//MAKE SLICE: make() allocates a zeroed array and returns a slice that refers to that array
    slc2 :=make([]int, 5)                   //[0 0 0 0 0]
    fmt.Println(slc2)

//APPEND TO SLICE: append(slice, element). Append new element to slice
    slc3 := []int{10,20,30,40,50}           //[10 20 30 40 50 60]
    slc3 = append(slc3,60)
    fmt.Println(slc3)
}
```

===== 2D Vector
```go
  // Method-1: Declare a 2D vector
  var test [][]int     
  
  // Method-2: Declare an empty 2D vector
  test := make([][]int, rows)
  // Initialize each row with specific length
  for i := range vector {
    test[i] = make([]int, cols)
  }
  
  // Method-3: Declare an empty 2D vector
  var test [][]int
  // Initialize each row with specific length
  for i := 0; i < rows; i++ {
    test = append(test, make([]int, cols))
  }


  // Initialize the 2D vector with values
  test = [][]int {
    1,2,3
    4,5,6
  }
  
  // Accessing elements in the 2D vector
  fmt.Println(vector[0][0]) // Output: 1
```

==== Heaps (implemented using slice)
The standard library doesn't provide a heap implementation, but you can create your own heaps using slices 

==== Queue (implemented using slice)
```go
package main
import "fmt"
type test struct {		//Declare a struct having slice which will act as queue
    q []int
}
func Constructor() test {
    return test{}
}
func (this *test) Push(x int)  {
    this.q = append(this.q, x)		//Push() append x to queue
}
func (this *MyStack) Pop() {
    this.q = this.q[1:]   		//Pop() Remove 1st element
}
func (this *MyStack) Top() int {
    return this.q[0]			//Top()
}
func (this *MyStack) Empty() bool {	//Size()
    if len(this.q) == 0 {
        return true
    }
    return false
}
```

==== Stack (implemented using slice)


=== (struct = class)
- Class is defined as struct type. Example: Person is defined of type struct.
- The struct type can be considered similar to a class, as it allows you to define fields and associated methods.
```go
package main
import "fmt"

type student struct {		// Define a struct type
	name string
	age  int
	marks []int		// slice = dynamic ints
	misc []interface{}	// misc is a slice that can hold values of any type
}

// Define a method associated with the Person struct
// To associate a method with a struct, define a method with a receiver type that matches the struct type.
func (p Person) SayHello() {
	fmt.Printf("Hello, my name is %s and I am %d years old.\n", p.name, p.age)
}

func main() {
	// Create a new instance of Person
	person := Person{name: "John", age: 30}

	// Call the SayHello method
	person.SayHello()
}
```

==== Linked Lists
Not a built-in type, you can implement linked lists in Go using structs and pointers.

====== link:https://github.com/amitkumar50/amitkumar50.github.io/blob/source/docs/DS_Questions/Data_Structures/Linked_List/Compared_c%2B%2B_rust_python_go.html[Operations]
