:toc:
:toclevels: 6

== Collections
go library provides built-in collection types to handle different data structures.

=== Array (fixed size)
* An array in Go is a fixed-size collection of elements of the same type. Once you define the size of an array, it cannot be changed
```go
func main() {
  arr := [6]int{1,2,3,4,5,6}    //[n values] type {}
  var len = len(arr);
}
```

=== channels
- Communication and synchronization between goroutines=Tasks in Rust (concurrently executing functions). They provide a way to send and receive data safely between goroutines.

=== Maps / Dictionary(Python) / unordered_map(C++) / Hash_map(Rust)

==== Sets
Go doesn't have a built-in set data type, but you can simulate sets using maps.

=== link:https://code-with-amitk.github.io/Languages/Programming/Go/Collections.html#slices[Slice [] (Dynamic Array) = C++(vector`<int>`) = Rust(vec`<i32>`)]
==== link:https://code-with-amitk.github.io/Languages/Programming/Go/Collections.html#slices[2D Vector]

==== Heaps (implemented using slice)
The standard library doesn't provide a heap implementation, but you can create your own heaps using slices 

==== Queue (implemented using slice)
```go
package main
import "fmt"
type test struct {		//Declare a struct having slice which will act as queue
    q []int
}
func Constructor() test {
    return test{}
}
func (this *test) Push(x int)  {
    this.q = append(this.q, x)		//Push() append x to queue
}
func (this *MyStack) Pop() {
    this.q = this.q[1:]   		//Pop() Remove 1st element
}
func (this *MyStack) Top() int {
    return this.q[0]			//Top()
}
func (this *MyStack) Empty() bool {	//Size()
    if len(this.q) == 0 {
        return true
    }
    return false
}
```

==== link:https://code-with-amitk.github.io/Languages/Programming/C++/STL/Containers/Container_Adoptors/stack.html[Stack (implemented using slice)]


=== (struct = class)
- Class is defined as struct type. Example: Person is defined of type struct.
- The struct type can be considered similar to a class, as it allows you to define fields and associated methods.
```go
package main
import "fmt"

type student struct {		// Define a struct type
	name string
	age  int
	marks []int		// slice = dynamic ints
	misc []interface{}	// misc is a slice that can hold values of any type
}

// Define a method associated with the Person struct
// To associate a method with a struct, define a method with a receiver type that matches the struct type.
func (p Person) SayHello() {
	fmt.Printf("Hello, my name is %s and I am %d years old.\n", p.name, p.age)
}

func main() {
	// Create a new instance of Person
	person := Person{name: "John", age: 30}

	// Call the SayHello method
	person.SayHello()
}
```

==== Linked Lists
Not a built-in type, you can implement linked lists in Go using structs and pointers.

====== link:https://github.com/amitkumar50/amitkumar50.github.io/blob/source/docs/DS_Questions/Data_Structures/Linked_List/Compared_c%2B%2B_rust_python_go.html[Operations]
