:toc:
:toclevels: 6

=== link:https://code-with-amitk.github.io/System_Design/Concepts/Databases/SQL_vs_NoSQL.html[SQL/Relational/Structured vs noSQL/nonRelational/unStructured]
Today most organization are using SQL+noSQL DB combinations. 2019 stats:   MySQL + MongoDB: 34.15%,  MySQL + PostgreSQL: 9.76%

==== link:https://code-with-amitk.github.io/System_Design/Concepts/Databases/SQL/SQL_Issues.html[1. SQL cannot store Huge data?]
==== link:https://code-with-amitk.github.io/System_Design/Concepts/Databases/SQL/SQL_Issues.html[2. Why SQL cannot be scaled Horizontally?]
==== link:https://code-with-amitk.github.io/System_Design/Concepts/Databases/[Stored Procedures and Functions in postgresql]

=== Object vs Block vs File storage

|===
|DB | Object | Block | File

|Examples | Amazon S3,ceph, openstack swift    | Amazon EBS, SAN-Arrays   |  Amazon EFS 
|Stores |Object{unique_key,metaData+data}| raw blocks(xfs,ext4 etc). Only part that changed need to be updated. | data in file, with limited meta-data 
|Disadv|When ever there is small change in object(eg:video), whole object needed to be reuploaded. if object is 80GB then lot of time wasted in uploading||
|Adv||Only part that is changed need to uploaded. if block is 80GB and small part is changed, then uploading takes very less time|
|Scaling | Easy | Tough(on high volume becomes unmanagable) | 
|Suitable for |objects can be: images,videos,text files,docs,photos,songs |files,docs | 
|Consistency | Eventual consistent | Strongly consistent| 
|Use cases |Occasional Changes & Storage|Making large RW changes in file and storing frequently.| 
|===


=== Database vs Datawarehouse
```c
                 |     Database                            | Datawarehouse
-----------------|-----------------------------------------|-------------------
Purpose          | Stores customer data                    | helps analyze data
Contians         | related data                            | Historical & commutative data
Orientation      | application-oriented-collection of data | subject-oriented collection of data
Uses             | Online Transactional Processing (OLTP)  |  Online Analytical Processing (OLAP)
Modelling Techniques | ER modeling techniques              | data modeling
used 
```

=== IMDB(In Memory DB) / MMDB(Main Memory DB) / Embedded DB
* Stores all data in main memory/RAM not on hard-disk. 
* Examples: VoltDB, [Redis](/System-Design/Concepts/Cache).
** Why Redis is cache & imdb both? Redis has features of a Cache plus processing/querying capabilities. Redis supports multiple data structures and you can query the data in the Redis (examples like get last 10 accessed items, get the most used item etc).
* *Advantages:* Faster. Since disk access is always slower than RAM
* *Applications?* Where response time is critical. Eg: Telecom equiments, Jet communications etc
* *Disadvantages:* 
** _1. Availability Problem?_ Since RAM is volatile(Means data is lost as power is gone or some failure). Solution:
```c
1a. Snapshot files OR checkpoint images, which record the state of the database at a given moment in time.
1b. Transaction logging, which records changes to the database in a journal file
1c. Replication
```
** _2. Expensive:_ RAM is always costlier than Disk, Huge amounts cannot be stored here.
* *IMDB vs link:/System-Design/Concepts/Cache[DBCache]:** DBCache stores: Mostly used, less frequently changing data is stored in cache. IMDB stores: Frequently changing data.

== link:https://code-with-amitk.github.io/System_Design/Concepts/Databases/Indexing/[Indexing, Reverse Indexing]
