:toc:
:toclevels: 6

== constexpr (constant expression)
* Tells compiler that function or variable should be evaluated at compile time, allowing the compiler to perform computations during compilation rather than at runtime.
* But function body should not contain any code which need runtime calculations.
```c
// Below code is not candidate of constexpr
constexpr int dynamicSquare(int x) {
    return x * time(nullptr);  // Invalid, time() is not constexpr
}  
```

=== Constexpr vs Macro
* Macros in C++ are a form of text substitution done by the preprocessor
* Macros are not subject to the same rules and restrictions as constexpr
* Macros replace code at the preprocessing stage, and they don't have a clear understanding of the C++ language constructs leading to potential issues like unintended side effects and lack of type safety
* More error-prone due to their text substitution nature and lack of type safety. They are not guaranteed to be evaluated at compile time
```cpp
#define SQUARE(x) ((x) * (x))
int main() {
    int result = SQUARE(5 + 1);  // Expanded to (5 + 1 * 5 + 1), unexpected behavior
    // ...
} 
```

=== Use cases of constexpr
==== a. Compile-Time Evaluation
```c
constexpr int square(int x) {
    return x * x;
}

int main() {
    constexpr int result = square(5);  // Computed at compile time
    // ...
} 
```
==== b. Array initialization
```c
constexpr int size = 5;
int array[size] = {1, 2, 3, 4, 5};  // Compile-time initialization 
```
==== c. Constant Expressions
```cpp
//constexpr can be used to define constants, 
allowing them to be used in contexts where only constant expressions are allowed
constexpr double pi = 3.14159;
```
==== d. Template Metaprogramming
```cpp
//generate code at compile time
template 
constexpr int factorial() {
    return N == 0 ? 1 : N * factorial();
}

int main() {
    constexpr int result = factorial<5>();  // Computed at compile time
    // ...
}   
```
==== e. Performance Optimization
```cpp
//improved performance by allowing the compiler to optimize and eliminate runtime computations
constexpr int computeValue() {
    // Some computation
    return result;
}

int main() {
    constexpr int value = computeValue();  // Computed at compile time
    // ...
}  
```

=== const vs constexpr variable
* const: Whose value remains same through out the program
* constexpr: variable whose value is derived at compile-time & initialized
```cpp
/////////const variable/////////
int main(){
 int a;
 cin >> a;
 const int b = a;   //Problem: How b is const if its value can be changed at runtime?
}
 
////////constexpr variable///////
int main() {
 //constexpr int c = a;  //error: uninitialized const ‘c’
 //constexpr int c;      // error: uninitialized const ‘c’
 constexpr int c = 1;
}
```
=== constexpr char`*`
constexpr variable need to be initialized by constexpr function. Since constexpr variable's value should be derived at compile time.
```cpp
  constexpr char* p = new char(5);  //Compilation error. ‘void* operator new(std::size_t)’ is non-constexpr function
  constexpr char a[] = "amit";      //Ok
```

=== constexpr function
* It return value should be computable at compile time only.
* *RULES?*
** constexpr function or constructor is implicitly inline.
** constexpr function accepts and returns only literal-types.
** constexpr functions cannot be virtual
** A constructor can't be defined as constexpr when the enclosing class has any virtual base classes.
** The body can be defined as = default or = delete.
** The body can contain no goto statements or try blocks.
** constexpr function return value can be collected in const variable.
* *Problem:*
```cpp
/////////////const function//////////////
const int fun(){        //Function is not const because return depends on runtime
  int b;
  cin>>b;
  return b;              //NO ERROR
}

/////////////constexpr function//////////
constexpr int fun(){
  //int b;               //error: uninitialized variable ‘b’ in ‘constexpr’ function
  int b = 10;
  return b;  
}

int main(){
  const float d = fun(2);
}
```

=== RELAXING CONSTRAINTS ON CONSTEXPR FUNCTION(C++14)
* In C++11, constexpr function bodies could only contain a very limited set of syntaxes, including (but not limited to): typedefs, using, and a single return statement. 
* In C++14, the set of allowable syntaxes expands greatly to include the most common syntax such as if statements, multiple returns, loops, etc.                
** RETURN TYPE: C++14: Requires constexpr variables to be of literal type(the standard doesn't define a named requirement with this name. This can be scalar,reference type,array of literal type).
