:toc:
:toclevels: 6

=== link:https://youtu.be/e53lYMVQGO0[Self Video]

=== link:https://leetcode.com/problems/counting-bits/description/[338. Counting Bits]
- Given an integer n, return an array ans of length n + 1 such that for each i (0 < = i < = n), ans[i] is the number of 1's in the binary representation of i.
* *Always Do as per REQUIREMENT*
** Solution should be better than O(n log n). Can you do it in *linear time O(n)* and possibly in a single pass?
** Can you do it without using any built-in function (i.e., like __builtin_popcount in C++)?
```c
Example 1:
Input: n = 2
Output: [0,1,1]
Explanation:
0 --> 0
1 --> 1
2 --> 10
```
==== What is meaning of O(n)?
* Without checking bits of number, we should tell on bits of number.
```c
Example: num = 6 = 00000000 00000000 00000000 00000110
Method-1: Left shift 1 and perform Bitwise &, We need 32 shifts for every number.

Requirement: Can we do without looking at bits, ie avoid this 32 time shift?
```

=== Approach-1. Divide by 2. O(nlogn)      //But Requirement is O(n)
==== Logic
```c
          -------
        2/  6        rem=0

          -------  
        2/  3        rem=1

          -------  
        2/  1        rem=1
6 = 110
```
==== Complexity
* *Time: O(nlogn):* With every divide by 2 we are going half and for n numbers

=== Approach-2. O(n*32). Bitwise & with 1 //But Requirement is O(n)
==== Logic
* Take 1, left shift perform & and count.

==== Code
===== CPP
```cpp
class Solution {
public:
    int FindOnes(int a){
        int i = 1, k = 1;
        int ones = 0;
        while (k++ != sizeof(int)*8) {
            if (a & i)
                ones++;
            i = i<<1;
        }
        return ones;
    }
    vector<int> countBits(int n) {
        vector<int> vecOut;
        for (int i=0;i<n+1;++i){
            vecOut.push_back(FindOnes(i));
        }
        return vecOut;
    }
};
```

===== Rust
```rs
use std::mem;
impl Solution {
    pub fn count_bits(a: i32) -> Vec<i32> {
    let mut v = vec![0; (a as usize)+1];
    let mut ones:i32 = 0;
    let mut i:i32 = 1;
    let mut k:i32 = 1;

    for var in 1..a+1 {
        while k as usize != mem::size_of::<i32>()*8 {
            if var & i > 0 {
                ones += 1;
            }
            i = i << 1;
            k += 1;
        }
        v[var as usize] = ones;
        ones = 0;   
        i=1;
        k=1;
    }
    v
    }
}
```

=== link:/Languages/Programming_Languages/C/Bitwise/Count_on_Bits/README.adoc[Approach-3. O(n*(number of ON bits)). Hamming Weight]

=== Approach-4. O(n). Dynamic Programming
==== Logic
* Can we derive number of bits from prev calculated numbers
```c
number    bit    number of ON bits(dp)   Power of 2
0          0           0
1          1           1
2          10          1                y        //power of 2 will always have 1 bit ON
3 =2+1     11          2                         //number of ON bits=(no of ON bits in 2) + (no of ON bits in 1)
4          100         1                y
5 =4+1     101         2    
6 =4+2     110         2                        //4(100) + 2(10) = ON bits on 6=ON Bits in 4 + ON Bits in 2
7 =4+3     111         3
8          1000        1                y
9 =8+1     1001        2
10=8+2     1010        2
```
==== Complexity
* *Time:* O(n). For 0,1 only we need to write bits then we calculate without going into number
* *Space:* O(n). Same sized dp array is needed

==== Code
===== C++
```cpp
class Solution {
public:
    vector<int> countBits(int n) {
        vector<int> dp(n+1, 0);
        if (n==0)
            return dp;

        dp[1]=1;
        int present = 0;        //present pow of 2
        int next = 2;            //next pow of 2

        for (int i=2; i<=n; ++i) {
            if (i == next) {
                // if i is same as power of 2
                present = next;
                next *= 2;
                dp[i] = 1;
            } else {
                dp [i] = dp[i-present] + dp[present];
            }
        }
        return dp;
    }
};
```
===== Python
```py
class Solution:
    def countBits(self, n: int) -> List[int]:
        dp = [0] * (n + 1)
        if n == 0:
            return dp

        dp[1] = 1
        present = 0  # present pow of 2
        next = 2     # next pow of 2

        for i in range(2, n + 1):
            if i == next:
                present = next
                next *= 2
                dp[i] = 1
            else:
                dp[i] = dp[i - present] + dp[present]

        return dp
```
===== Rust
```rs
impl Solution {
    pub fn count_bits(n: i32) -> Vec<i32> {
        let mut dp = vec![0; (n as usize +1)]; 
        if n == 0 {
            return dp;
        }
        dp[1] = 1;

        let mut present:usize = 0;
        let mut next:usize = 2;

        for i in 2 .. n+1 {
            if i as usize == next {
                present = next;
                next *= 2;
                dp[i as usize] = 1;
            } else {
                dp[i  as usize] = dp[i as usize -present] + dp[present];
            }
        }
        dp
    }
}
```
===== Go
```rs
func countBits(n int) []int {
    dp := make([]int, n+1)
    for i:=0; i<n+1; i++ {
        dp[i] = 0;
    }
    if n == 0 {
        return dp;
    }

    dp[1] = 1;
    var present int = 0;
    var next int = 2;

    for i:=2; i<n+1; i++ {
        if i == next {
            present = next;
            next *= 2;
            dp[i] = 1;
        } else {
            dp[i] = dp[i-present] + dp[present];
        }
    }
    return dp;
}
```

===== C
```c
/**
 * Note: The returned array must be malloced, assume caller calls free().
 */
int* countBits(int n, int* returnSize){
    int *count = (int*) malloc(sizeof(int) *(n +1));
    count[0]=0;
    *returnSize = n+1;
    if (n==0)
        return count;

    count[1] = 1;
    int present = 0;        //present pow of 2
    int next = 2;  //next pow of 2

    for (int i=2; i<=n; ++i) {
        if (i == next) {
            present = next;
            next *= 2;
            count[i] = 1;
        } else {
            count [i] = count[i-present] + count[present];
        }
    }
    return count;
}
```
