:toc:
:toclevels: 6



== link:https://leetcode.com/problems/building-h2o/description/[1117. Building H2O]
- There are two kinds of threads: oxygen and hydrogen. Your goal is to group these threads to form water molecules.
- There is a barrier where each thread has to wait until a complete molecule can be formed. Hydrogen and oxygen threads will be given releaseHydrogen and releaseOxygen methods respectively, which will allow them to pass the barrier. These threads should pass the barrier in groups of three, and they must immediately bond with each other to form a water molecule. You must guarantee that all the threads from one molecule bond before any other threads from the next molecule do.
- In other words:
  - If an oxygen thread arrives at the barrier when no hydrogen threads are present, it must wait for two hydrogen threads.
  - If a hydrogen thread arrives at the barrier when no other threads are present, it must wait for an oxygen thread and another hydrogen thread.
- Write synchronization code for oxygen and hydrogen molecules that enforces these constraints.
```c
Example 1:
Input: water = "HOH"
Output: "HHO"
Explanation: "HOH" and "OHH" are also valid answers.

Example 2:
Input: water = "OOHHHH"
Output: "HHOHHO"
Explanation: "HOHHHO", "OHHHHO", "HHOHOH", "HOHHOH", "OHHHOH", "HHOOHH", "HOHOHH" and "OHHOHH" are also valid answers.
```

== Approach-1. Synchronization
=== Logic
* Initialize 2 variables (h=2, o=1) in class constructor
* Enter hydrogen() only when h>0
** On entering h--
** when h and o both becomes zero make (h=2,o=1)
* Enter oxygen() only when o>0
** On entering o--
** when h and o both becomes zero make (h=2,o=1)

=== Code
==== CPP. condition_variable
```cpp
class H2O {
    int h,o;
    mutex mtx;
    condition_variable cv;
public:
    H2O() {
        h = 2;
        o = 1;
    }
    void reset() {
        if (h==0 && o==0) {
            h=2;   
            o=1;
        }
    }

    void hydrogen(function<void()> releaseHydrogen) {
        unique_lock<mutex> ul(mtx);

        // Lambda, return true when you want to go inside, else false
        auto wait_condition = [this]() {
            if (h>0)
                return true;
            return false;
        };
        cv.wait(ul, wait_condition);

        // releaseHydrogen() outputs "H". Do not change or remove this line.
        releaseHydrogen();

        h -= 1;
        reset();
        ul.unlock();
        cv.notify_one();
    }

    void oxygen(function<void()> releaseOxygen) {
        unique_lock <mutex> ul(mtx);

        // Lambda, return true when you want to go inside, else false
        auto wait_condition = [this]() {
            if (o>0)
                return true;
            return false;
        };
        cv.wait(ul, wait_condition);

        // releaseOxygen() outputs "O". Do not change or remove this line.
        releaseOxygen();

        o -= 1;
        reset();     
        ul.unlock();
        cv.notify_one();
    }
};
```
