:toc:
:toclevels: 6

== link:https://leetcode.com/problems/fizz-buzz-multithreaded/description/[1195. Fizz Buzz Multithreaded]
You have the four functions:

* printFizz that prints the word "fizz" to the console,
* printBuzz that prints the word "buzz" to the console,
* printFizzBuzz that prints the word "fizzbuzz" to the console, and
* printNumber that prints a given integer to the console.

You are given an instance of the class FizzBuzz that has four functions: fizz, buzz, fizzbuzz and number. The same instance of FizzBuzz will be passed to four different threads:

* Thread A: calls fizz() that should output the word "fizz".
* Thread B: calls buzz() that should output the word "buzz".
* Thread C: calls fizzbuzz() that should output the word "fizzbuzz".
* Thread D: calls number() that should only output the integers.

Modify the given class to output the series [1, 2, "fizz", 4, "buzz", ...] where the ith token (1-indexed) of the series is:

* "fizzbuzz" if i is divisible by 3 and 5,
* "fizz" if i is divisible by 3 and not 5,
* "buzz" if i is divisible by 5 and not 3, or
* i if i is not divisible by 3 or 5.

Implement the FizzBuzz class:

* FizzBuzz(int n) Initializes the object with the number n that represents the length of the sequence that should be printed.
* void fizz(printFizz) Calls printFizz to output "fizz".
* void buzz(printBuzz) Calls printBuzz to output "buzz".
* void fizzbuzz(printFizzBuzz) Calls printFizzBuzz to output "fizzbuzz".
* void number(printNumber) Calls printnumber to output the numbers.
 
```c
Example 1:
Input: n = 15
Output: [1,2,"fizz",4,"buzz","fizz",7,8,"fizz","buzz",11,"fizz",13,14,"fizzbuzz"]

Example 2:
Input: n = 5
Output: [1,2,"fizz",4,"buzz"]
```

== Approach-1. CPP. condition_variable
=== Logic
* At start of each function check whether condition is satisfied or not. if condition is not satified donot enter into the function.
```c
    Divisbileby 3  5
    fizz        y  n
    buzz        n  y
    fizzbuzz    y  y
    number      n  n
```
* Take a variable i, increment value inside each function, Run until i<n
* Run in while(true) loop in each function and check above condition

=== Complexity
* Time: O(n)
* Space: O(1)

=== Code
==== CPP
```cpp
class FizzBuzz {
private:
    int n;
    mutex mtx;
    condition_variable cv;
    int i;
public:
    FizzBuzz(int n) {
        this->n = n;
        i = 1;
    }

    /*
                3  5
    fizz        y  n
    buzz        n  y
    fizzbuzz    y  y
    number      n  n
    */
    // printFizz() outputs "fizz".
    // printFizz() outputs "fizz".
    void fizz(function<void()> printFizz) {
        while (true) {
            unique_lock<mutex> ul(mtx);
            auto wait_cond = [this]() {
                if (i>n || (i % 3 == 0 && i % 5 != 0))
                    return true;
                return false;
            };
            cv.wait(ul, wait_cond);            
            if (i > n) 
                break;
            printFizz();
            ++i;
            ul.unlock();
            cv.notify_all();
        }
    }

    // printBuzz() outputs "buzz".
    void buzz(function<void()> printBuzz) {
        while (true) {
            unique_lock<mutex> ul(mtx);
            auto wait_cond = [this]() {
                if (i>n || (i % 3 != 0 && i % 5 == 0))
                    return true;
                return false;
            };
            cv.wait(ul, wait_cond);            
            if (i > n) 
                break;
            printBuzz();
            ++i;
            ul.unlock();
            cv.notify_all();
        }
    }

    // printFizzBuzz() outputs "fizzbuzz".
    void fizzbuzz(function<void()> printFizzBuzz) {
        while (true) {
            unique_lock<mutex> ul(mtx);
            auto wait_cond = [this]() {
                if (i>n || (i % 3 == 0 && i % 5 == 0))
                    return true;
                return false;
            };
            cv.wait(ul, wait_cond);            
            if (i > n) 
                break;
            printFizzBuzz();
            ++i;
            ul.unlock();
            cv.notify_all();
        }
    }

    // printNumber(x) outputs "x", where x is an integer.
    void number(function<void(int)> printNumber) {
        while (true) {
            unique_lock<mutex> ul(mtx);
            auto wait_cond = [this]() {
                if (i>n || (i % 3 != 0 && i % 5 != 0))
                    return true;
                return false;
            };
            cv.wait(ul, wait_cond);
            if (i > n)
                break;
            printNumber(i);
            ++i;
            ul.unlock();
            cv.notify_all();
        }
    }
};
```
