:toc:
:toclevels: 6

== link:https://leetcode.com/problems/split-linked-list-in-parts/description/[725. Split Linked List in Parts]
Given the head of a singly linked list and an integer k, split the linked list into k consecutive linked list parts.

The length of each part should be as equal as possible: no two parts should have a size differing by more than one. This may lead to some parts being null.

The parts should be in the order of occurrence in the input list, and parts occurring earlier should always have a size greater than or equal to parts occurring later.

Return an array of the k parts.
```c
Example-1:
Input: head = [1,2,3], k = 5
Output: [[1],[2],[3],[],[]]
Explanation:
The first element output[0] has output[0].val = 1, output[0].next = null.
The last element output[4] is null, but its string representation as a ListNode is [].

Example-2:
Input: head = [1,2,3,4,5,6,7,8,9,10], k = 3
Output: [[1,2,3,4],[5,6,7],[8,9,10]]
Explanation:
The input has been split into consecutive parts with size difference at most 1, and earlier parts are a larger size than the later parts.
```

=== Approach. O(n)
==== Logic
1. Find length of Linked list ie number of nodes.
2. Find length of each paritition = no_of_nodes/k
3. Find extra nodes which need to be distributed equally on 1st r parititions. r = no_of_nodes%k
4. Take 2 pointers (curr, prev). curr will traverse parts, prev will break next pointer(ie set to null) in output.

==== Complexity
- *Time:* O(n). Find length=O(n). Break linkedlist=O(n)
- *Space:* O(1)

==== Code
===== CPP
```cpp
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    vector<ListNode*> splitListToParts(ListNode* head, int k) {
        // Output vector to store k pointers of parts
        vector<ListNode*> out(k, nullptr);

        // Find number of nodes
        int no_of_nodes = 0;
        for (ListNode* node = head; node; node = node->next)
            no_of_nodes++;

        // Find minimum guaranteed size of each part = n
        int n = no_of_nodes/k;

        // Find total number of extra nodes = r
        // These will be spread among the first r parts
        // if (r>0) //remaining extra nodes
        //   Traverse n + 1 nodes
        // else
        //   Traverse n nodes
        int r = no_of_nodes%k;

        // Take 2 pointers curr, prev to traverse linkedlist
        // curr will store node in output vector
        // prev to break node->next
        ListNode *curr=head, *prev=head;

        for (int i = 0; curr!=nullptr && i < k; i++, r--) {
            // Store the current node as the start of the current part.
            out[i] = curr;

            // Traverse n + 1 nodes if there are remaining extra nodes (r > 0).
            // Otherwise, traverse only n nodes.
            for (int j = 0; j < n + (r > 0); j++) {
                prev = curr;
                curr = curr->next;
            }

            // Disconnect the current part from the rest
            // of the list by setting prev->next to nullptr.
            prev->next = nullptr;
        }
        return out;
    }
};
```

===== Go
```go
/**
 * Definition for singly-linked list.
 * type ListNode struct {
 *     Val int
 *     Next *ListNode
 * }
 */
func splitListToParts(head *ListNode, k int) []*ListNode {
    out := make([]*ListNode, k)
    for i:=0;i<k;i++ {
        out[i] = nil
    }

    // Find number of nodes
    no_of_nodes := 0
    for node := head; node != nil; node = node.Next {
        no_of_nodes += 1
    }

    // Find minimum guaranteed size of each part = n
    n := no_of_nodes/k

    // Find total number of extra nodes = r
    // These will be spread among the first r parts
    // if (r>0) //remaining extra nodes
    //   Traverse n + 1 nodes
    // else
    //   Traverse n nodes
    r := no_of_nodes%k
    
    // Take 2 pointers curr, prev to traverse linkedlist
    // curr will store node in output vector
    // prev to break node->next
    curr := head
    prev := head

    for i := 0; curr != nil && i < k; i, r = i+1, r-1 {
        // Store the current node as the start of the current part.
        out[i] = curr

        // Traverse n + 1 nodes if there are remaining extra nodes (r > 0).
        // Otherwise, traverse only n nodes.
        increment := 0
        if r > 0 {
            increment = 1
        }
        for j := 0; j < n + increment; j++ {
            prev = curr
            curr = curr.Next
        }

        // Disconnect the current part from the rest
        // of the list by setting prev->next to nil.
        prev.Next = nil
    }
    return out

}
```
