:toc:
:toclevels: 6

== Mint (Write heavy)
* Mint.com is a free, web-based personal financial management service, that allows its users to integrate with financial accounts to automatically extract their data, and manage their personal budget.
* This is write heavy(100:1), since most users do transaction on their bank accounts and read rearly on app.

=== 1. Requirements
==== Functional

[[req1]]
* Req-1. User can connect all financial accounts to mint

[[req2]]
* Req-2. Service extracts transactions from the account(daily updates)

3. Categorizes transactions: Allows manual category override by the user, No automatic re-categorization
4. Cashflow Analyses: Analyzes monthly spending, by category.
5. Budget: Users to manually set a budget, Sends notifications when approaching or exceeding budget. 

==== Non Functional
1. High availability, Scalable, Secure

==== Extended
1. Analytics, Suggestions, Predictions, Logging

=== 2. API Design (For every requirement)
link:https://github.com/amitkumar50/Code-examples/blob/master/Networking/OSI-Layers/Layer-7/Protocols/HTTP/README.adoc[HTTP Methods]

<<req1, add_account>> (mint_cust_id, struct user_info{account_info{bank_name, acnt_no, cust_name, ifsc_code}, phone_no}, validation_oauth_token, current_time_stamp)
```
POST https://lb_fqdn:port/v1/add_account?mint_cust_id=12312asa1&bank_name=hdfc&photo_url=https://photo.com/photo1.png&current_time_stamp=
```
<<req2, extract_transaction>> (mint_cust_id, service_token)
```
GET https://lb_fqdn:port/v1/extract_transaction?mint_cust_id=12312asa1&service_token=aaaaa
```

=== 3. BOE
[[qps]]
==== QPS(Queries/sec)
This is writes/sec
```
DAU = 100M. Active/sec = 100M/86400 = 1000 writes/sec
```

==== Storage Estimates (Writes/sec)
* All users are doing some transactions(ie writing to their bank accounts=Mint account)
```
1 write size = 8k(header)+10k(payload) =~ 20KB
1 day storage needed:   100M x 20KB = 2TB/day.
5 years storage neede:  2TB x (365x5 ~ 2000) = 4PB
```

==== Bandwidth Estimate (bytes coming into system/sec)
```
2TB/day. 2TB/86400 = 20MB/sec
```

==== Reads/sec. Outgoing Reads/sec. Outgoing data/sec
Since <<qps,Writes/sec = 1000>>
```
Reads/sec = 10
```
