:toc:
:toclevels: 5

== link:https://leetcode.com/problems/find-valid-matrix-given-row-and-column-sums/[1605. Find Valid Matrix Given Row and Column Sums]
You are given two arrays rowSum and colSum of non-negative integers where rowSum[i] is the sum of the elements in the ith row and colSum[j] is the sum of the elements of the jth column of a 2D matrix. In other words, you do not know the elements of the matrix, but you do know the sums of each row and column.

Find any matrix of non-negative integers of size rowSum.length x colSum.length that satisfies the rowSum and colSum requirements.

Return a 2D array representing any matrix that fulfills the requirements. It's guaranteed that at least one matrix that fulfills the requirements exists.
```c
Example 1:
Input: rowSum = [3,8], colSum = [4,7]
Output: [[3,0],
         [1,7]]
Explanation: 
0th row: 3 + 0 = 3 == rowSum[0]
1st row: 1 + 7 = 8 == rowSum[1]
0th column: 3 + 1 = 4 == colSum[0]
1st column: 0 + 7 = 7 == colSum[1]
The row and column sums match, and all matrix elements are non-negative.
Another possible matrix is: [[1,2],
                             [3,5]]

Example 2:
Input: rowSum = [5,7,10], colSum = [8,6,8]
Output: [[0,5,0],
         [6,1,0],
         [2,0,8]]
```

== Approach. O(mn). Take min number from row,col
=== Logic
```c
rowSum=[3,8]. colSum=[4,7]
```
* Output array would be of size=2x2. Because rowSum.size()=2, colSum.size()=2. Init to 0
```c
  0  0
  0  0
```
* We will iterate over rowSum & colSum using 2 variables i,j.
* Fill out[i][j] with min of rowSum, colSum element. out[i][j] = min(rowSum[i], colSum[j])
** Since element is placed we will reduce this element from both rowSum and colSum
```
  rowSum=[3,8]. colSum=[4,7]
  3  0
  0  0

  After Placing 3:  rowSum=[3-3,8]. colSum=[4-3,7]  =  [0,8][1,7]
```
* if either rowSum or colSum becomes 0, we will move to next row or coloumn and place min(rowSum[i], colSum[j])
```c
  i = 1
  j = 0

  3  0
  1  0
```
* so on

=== Complexity
* Time: O(mn)
* Space: O(1)

=== Code
==== CPP98
```cpp
class Solution {
public:
    // rowSum=[3,8]. colSum=[4,7]
    vector<vector<int>> restoreMatrix(vector<int>& rowSum, vector<int>& colSum) {
        int rows = rowSum.size();
        int cols = colSum.size();

        // Create output array
        vector<vector<int>> out (rows, vector<int>(cols, 0));

        // Iterate to create out array
        int i=0, j=0;
        while (i < rows && j < cols) {
            int val = min(rowSum[i], colSum[j]);
            out[i][j] = val;
            rowSum[i] -= val;
            colSum[j] -= val;
            
            // Since row[0]=0, We will move to next row
            if (rowSum[i] == 0)
                i += 1;
            if (colSum[j] == 0)
                j += 1;
        }
        return out;
    }
};
```
==== Rust
```rs
use std::cmp;
impl Solution {
    pub fn restore_matrix(mut row_sum: Vec<i32>, mut col_sum: Vec<i32>) -> Vec<Vec<i32>> {
        let rows = row_sum.len();
        let cols = col_sum.len();
        let mut i = 0;
        let mut j = 0;
        let mut out:Vec<Vec<i32>> = vec![vec![0; cols]; rows];

        while i<rows && j<cols {
            let val = cmp::min(row_sum[i], col_sum[j]);
            out[i][j] = val;
            row_sum[i] -= val;
            col_sum[j] -= val;
            if row_sum[i] == 0 {
                i += 1;
            }
            if col_sum[j] == 0 {
                j += 1;
            }
        }
        out
    }
}
```
==== Python
```py
class Solution:
    def restoreMatrix(self, rowSum: List[int], colSum: List[int]) -> List[List[int]]:
        rows = len(rowSum)
        cols = len(colSum)

        out = [[0 for _ in range(cols)] for _ in range(rows)]

        # Iterate to create out array
        i=0
        j=0

        while i < rows and j < cols:
            val = min(rowSum[i], colSum[j])
            out[i][j] = val
            rowSum[i] -= val
            colSum[j] -= val
            
            # Since row[0]=0, We will move to next row
            if rowSum[i] == 0:
                i += 1
            if colSum[j] == 0:
                j += 1
        return out
```
==== Go
```go
func mini(a, b int) int {
    if a < b {
        return a
    }
    return b
}
func restoreMatrix(rowSum []int, colSum []int) [][]int {
    rows := len(rowSum)
    cols := len(colSum)

    // Create output array
    out := make([][]int, rows)
    for i := range out {
        out[i] = make([]int, cols)
    }

    // Iterate to create out array
    i, j := 0, 0
    for i < rows && j < cols {
        val := min(rowSum[i], colSum[j])
        out[i][j] = val
        rowSum[i] -= val
        colSum[j] -= val

        // Move to the next row or column if their sum is 0
        if rowSum[i] == 0 {
            i += 1
        }
        if colSum[j] == 0 {
            j += 1
        }
    }
    return out
}
```
