:toc:
:toclevels: 6

== SOLID Principles
=== a. Single Responsibility 
Every module/class should have one responsibility and should work on single part of functionality provided by software. Microservices are build around this.

=== b. Open-Closed
* Software entities(classes/modules) should be open for extension but closed for modification.
** Extension: Existing classes can be extended/coupled with any new behavior.
** Modifications: Coders have spent day & night for making code bug free & fast. We cannot get code changes in existing now.
* **How Achieved?** By creating a abstract class and every derived class has its own custom implementation.
** Example: Calculate area of any shape. Initially we have only Rectangle. We can include circle, Triagle, polygon etc later on and add new code, without touching abstract class code.
```cpp
class Shape {   //Pure Virtual class. Abstract class
public:
        virtual double Area() = 0;
};
class Rectangle : public Shape {
        int width, height;
public:
        Rectangle(int w, int h):width(w), height(h){}
        double Area(){
                return width*height;
        }
};
class Circle : public Shape {
        int radius;
public:
        Circle(int r):radius(r){}
        double Area(){
                return radius*radius*3.14;
        }
};
int main(){
        Rectangle r(4,5);
        cout << r.Area() << "\n";
        Circle c(3);
        cout << c.Area();
}
```

=== c. Liskov Substitution Principle (LSP)
* Derv class object can be used in place of base class object without any issues.
* link:/Languages/Programming_Languages/c++/Characteristics_of_OOPS/Polymorphism/Dynamic_RunTime/README.md[Example C++]
  
=== d. Interface Segregation Principle (ISP) 
* Interface in C++ = Base class having Pure Virtual Function.
* Interface(base class having PVF) should be designed to be specific to the needs of the client(Derived classes) that use them.
** ie if derived class implements an interface, it should only implement methods that are needed. Derived class should not be forced to implement methods which it does not use.

==== Example
===== Voilation of ISP
Derv class only need fun1(), But below code will not compile if fun2() is not overridden in derived class.
```cpp
#include <iostream>
using namespace std;
class IBase {
  virtual void fun1() = 0;
  virtual void fun2() = 0;
};
class derv:public base {
  public:
    void fun1() override { cout << "derv fun1\n"; }
};
int main() {
    derv oDerv;
    oDerv.fun1();
    return 0;
}
$ g++ test.cpp
'virtual void base::fun2()' must be defined
```
===== Correct Approach (as per ISP)
derv class uses the interface which it wants
```c
class IBase1 {
  virtual void fun1() = 0;
};
class IBase2 {
  virtual void fun2() = 0;
};
class derv: public IBase1, public IBase2 .. {
}
```

=== e. Dependency Inversion Principle (DIP)
* High-level modules should not depend on low-level modules. Both should depend on abstractions(means Interface(class having PVF).
* Abstractions should not depend on details. Details should depend on abstractions.
==== Example (Notification Service)
Let's suppose there is a notification service which sends (Email)
===== Voilation of DIP
* Problems with approach:
** NotificationSender class is tightly coupled to the Email class. if we want to send SMS, we need to modify NotificationService class.
```cpp
#include <iostream>
#include <string>
using namespace std;
class Email {
  public:
    void send() { cout<<"Email sent"; }
};
class NotificationService {
  Email email;
  public:
    void send() { email.send(); }
};
int main() {
    NotificationService obj;
    obj.send();
    return 0;
}
```
==== Solution to above problem using DIP
* Decoupling: The NotificationSender class now depends only on the INotification interface, not on concrete implementations like Email 
* Flexible: We can easily add new notification types (e.g. SMS) without modifying NotificationService class
```cpp
#include <iostream>
#include <string>
using namespace std;
class INotification {
  public:
    virtual void send() = 0;
    virtual ~INotification() = default;
};
class Email : public INotification {
  public:
    void send() override { cout<<"Email sent"; }
};
class NotificationService {
  INotification& OINotification;
  public:
    NotificationService(INotification& n) : OINotification(n) {}
    void send() { OINotification.send(); }
};
int main() {
    Email email;
    NotificationService obj(email);
    obj.send();
    return 0;
}
```

== Other Principles
=== a. DRY(Donot repeat yourself) 
If you have a block of code in more than two places, consider making it a separate method

=== c. ODR(One Definition Rule)    
A compiled source code(also called compilation unit/translation unit) will have only 1 definition but can have multiple declarations.

=== d. Separation of concerns
Dividing code into distinct sections so that each section addresses separate concern. Concern here means problems that code is going to address  

== Head 1st Design Patterns Principles
=== 1. Identify the aspects of application that vary and separate them from what stays the same.
=== 2. Program to an interface, not an implementation.
--- 3. Favour composition over inheritance

== RAII(Resource Acquisition is Initialization) OR SBRM(Scope Bound Resource Management):
* Resource(Anything that exists in limited supply eg: socket, files, disk, mutex, Heap, threads etc) lifetime should be bounded to object lifetime. Means when object's lifetime ends, resources are also freed in reverse order of allocation.
* resource would be available to any function that accesses the object. 
* How this is achieved? Acquire resources in constructor, release in destructor or smart pointer.
