:toc:
:toclevels: 6

=== link:https://leetcode.com/problems/implement-stack-using-queues/description/[225. Implement Stack using Queues]
- Implement a last-in-first-out (LIFO) stack using only two queues. The implemented stack should support all the functions of a normal stack (push, top, pop, and empty).
- Implement the MyStack class:
```c
void push(int x) Pushes element x to the top of the stack.
int pop() Removes the element on the top of the stack and returns it.
int top() Returns the element on the top of the stack.
boolean empty() Returns true if the stack is empty, false otherwise.
``
- Notes: You must use only standard operations of a queue, which means that only push to back, peek/pop from front, size and is empty operations are valid.
Depending on your language, the queue may not be supported natively. You may simulate a queue using a list or deque (double-ended queue) as long as you use only a queue's standard operations.
```c
Example 1:
Input
["MyStack", "push", "push", "top", "pop", "empty"]
[[], [1], [2], [], [], []]
Output
[null, null, null, 2, 2, false]
```

=== Approach-1. Using 1 queue
==== Logic
* 1. Take 2 queues q1, q2. {1,2,3}
* 2. push(). Push all elements in q1
```c
q1 {1,2,3}
q2 {}
```
* 3. top(). 
** 3a. Pop all elements from q1 except last and push in q2.
** 3b. return last element from q1
** 3c. Push last element to q2, empty q1 and again 
** 3d. Insert all elements from q2 to q1
```c
q1 {3}
q2 {1,2}        //3a
return top = 3    //3b

q1 {}            //3c
q2 {1,2,3}      

q1 {1,2,3}      //3d. Insert all elements from q2 to q1
q2 {}
```
* 4 pop()
** 4a. Pop all elements from q1 except last and push in q2.
** 4b. return last element from q1 and pop
** 4c. insert all elements from q2 to q1
```c
q1 {3}
q2 {1,2}                //4a

return top = 3 & pop()   //4b
q1 {}
q2 {1,2}

q1 {1,2}                //4c. Insert all elements from q2 to q1
q2 {}
```

==== Complexity
===== Time
* O(1)

===== Space: O(n)
* 2 queues of size n

==== Code
===== CPP
```cpp
class MyStack {
    queue<int> q1, q2;

    //Insert all elements from q2 to q1
    void PushFromQ2toQ1() {
        while (!q2.empty()) {
            q1.push(q2.front());
            q2.pop();
        }
    }

    //Pop all elements from q1 except last and push in q2. This last element is top()
    int getQ1Last() {
        while (q1.size() > 1) {
            q2.push(q1.front());
            q1.pop();
        }
        return q1.front();
    }
public:
    MyStack() {}

    //Push all elements in q1
    void push(int x) {
        q1.push(x);
    }

    int pop() {
        int ele = getQ1Last();      //Pop all elements from q1 except last and push in q2. This last element is top()
        q1.pop();                  //Remove last element from q1
        PushFromQ2toQ1();          //Insert all elements from q2 to q1
        return ele;
    }

    int top() {
        int ele = getQ1Last();    //Pop all elements from q1 except last and push in q2. This last element is top()
        q2.push(ele);            //Push last element to q2, empty q1 and again 
        q1.pop();                //empty q1
        PushFromQ2toQ1();        //Insert all elements from q2 to q1
        return ele;
    }
    
    bool empty() {
        if (q1.empty())
            return true;
        return false;
    }
};
```
===== Python
```py
import queue
class MyStack:

    def __init__(self):
        self.q = queue.Queue()

    def push(self, x: int) -> None:
        self.q.put(x)
        for _ in range(0, self.q.qsize()-1):
            self.q.put(self.q.get())

    def pop(self) -> int:
        return self.q.get()     # get() = top+pop

    def top(self) -> int:
        top_element = self.q.get()  # get=top + pop
        self.q.put(top_element)     # push elment again, Now this comes at end

        # Move top_element to front
        for _ in range(0, self.q.qsize() - 1):
            self.q.put(self.q.get())
        return top_element

    def empty(self) -> bool:
        if self.q.empty() == True:
            return True
        return False


# Your MyStack object will be instantiated and called as such:
# obj = MyStack()
# obj.push(x)
# param_2 = obj.pop()
# param_3 = obj.top()
# param_4 = obj.empty()
```
