:toc:
:toclevels: 6

=== link:https://leetcode.com/problems/implement-stack-using-queues/description/[225. Implement Stack using Queues]
- Implement a last-in-first-out (LIFO) stack using only two queues. The implemented stack should support all the functions of a normal stack (push, top, pop, and empty).
- Implement the MyStack class:
```c
void push(int x) Pushes element x to the top of the stack.
int pop() Removes the element on the top of the stack and returns it.
int top() Returns the element on the top of the stack.
boolean empty() Returns true if the stack is empty, false otherwise.
``
- Notes: You must use only standard operations of a queue, which means that only push to back, peek/pop from front, size and is empty operations are valid.
Depending on your language, the queue may not be supported natively. You may simulate a queue using a list or deque (double-ended queue) as long as you use only a queue's standard operations.
```c
Example 1:
Input
["MyStack", "push", "push", "top", "pop", "empty"]
[[], [1], [2], [], [], []]
Output
[null, null, null, 2, 2, false]
```

=== Approach-1. Using 1 queue
==== Logic
* 1. push(). Take 1 queue. Push all elements to same
** if size > 1
*** Remove elements from front and push at back of queue
```c
q {1}        //Push 1
q {1 2}      //Push 2 
    {2 1}        //Remove 1 and push back

q {2 1 3}        //Push 3
    {1 3 2}        //Remove 2, push back
    {3 2 1}        //Remove 1, push back
```

==== Complexity
===== Time
* O(1)

===== Space: O(n)
* queue size=n

==== Code
===== CPP
```cpp
class MyStack {
    queue<int> q;
public:
    MyStack() {      
    }
    
    void push(int x) {
		q.push(x);        // Push all elements to queue
        // Remove elements from front and push at back of queue
		for(int i=0;i<q.size()-1;++i){
			q.push(q.front());
			q.pop();
		}
    }
    int pop() {
        int ele = q.front();
        q.pop();
        return ele;
    }
    
    int top() {
        return q.front();
    }
    
    bool empty() {
        if (q.empty())
            return true;
        return false;
    }
};

/**
 * Your MyStack object will be instantiated and called as such:
 * MyStack* obj = new MyStack();
 * obj->push(x);
 * int param_2 = obj->pop();
 * int param_3 = obj->top();
 * bool param_4 = obj->empty();
 */
```
===== Python
```py
import queue
class MyStack:

    def __init__(self):
        self.q = queue.Queue()

    def push(self, x: int) -> None:
        self.q.put(x)
        for _ in range(0, self.q.qsize()-1):
            self.q.put(self.q.get())

    def pop(self) -> int:
        return self.q.get()     # get() = top+pop

    def top(self) -> int:
        top_element = self.q.get()  # get=top + pop
        self.q.put(top_element)     # push elment again, Now this comes at end

        # Move top_element to front
        for _ in range(0, self.q.qsize() - 1):
            self.q.put(self.q.get())
        return top_element

    def empty(self) -> bool:
        if self.q.empty() == True:
            return True
        return False


# Your MyStack object will be instantiated and called as such:
# obj = MyStack()
# obj.push(x)
# param_2 = obj.pop()
# param_3 = obj.top()
# param_4 = obj.empty()
```
===== Rust
```rs
use std::collections::VecDeque;

pub struct MyStack {
    dq: VecDeque<i32>,
}

impl MyStack {
    fn new() -> Self {
        Self {
            dq: VecDeque::new(),
        }
    }

    fn push(&mut self, x: i32) {
        self.dq.push_back(x);
        for _ in 0..self.dq.len() - 1 {
            if let Some(front) = self.dq.pop_front() {
                self.dq.push_back(front);
            }
        }
    }

    fn pop(&mut self) -> i32 {
        if let Some(front) = self.dq.pop_front() {
            front
        } else {
            0
        }
    }

    fn top(&self) -> i32 {
        *self.dq.front().unwrap_or(&0)
    }

    fn empty(&self) -> bool {
        self.dq.is_empty()
    }
}
```
