:toc:
:toclevels: 6

== link:https://leetcode.com/problems/evaluate-reverse-polish-notation/[150. Evaluate Reverse Polish Notation]
* Evaluate the value of an arithmetic expression in Reverse Polish Notation.
* Valid operators are `+, -, *, and /`. Each operand may be an integer or another expression.
* It is guaranteed that the given RPN expression is always valid. That means the expression would always evaluate to a result, and there will not be any division by zero operation.
```c
Example 1:
Input: tokens = ["2","1","+","3","*"]
Output: 9
Explanation: ((2 + 1) * 3) = 9

Example 2:
Input: tokens = ["4","13","5","/","+"]
Output: 6
Explanation: (4 + (13 / 5)) = 6

Example 3:
Input: tokens = ["10","6","9","3","+","-11","*","/","*","17","+","5","+"]
Output: 22
Explanation: ((10 * (6 / ((9 + 3) * -11))) + 17) + 5
= ((10 * (6 / (12 * -11))) + 17) + 5
= ((10 * (6 / -132)) + 17) + 5
= ((10 * 0) + 17) + 5
= (0 + 17) + 5
= 17 + 5
= 22
```

== Approach-1, Postfix conversion using stack
* What is Polish Notation? This is prefix notation
```c
3+4 = +34
```
- **Reverse Polish Notation?** Postfix notation. Question is evaluate postfix expression
```c
3+4 = 34+
```

=== Logic
|| Operator(+-) Operand(3,4)
* Push operands on stack
* Once operator is recieved, pop top 2 operands and apply operator on operands and again push on stack
```c
["2","1","+","3","*"]

Push on stack
| 1 |
| 2 |

Operator recieved: Pop top 2 and apply operator. Push on stack
| 3 |

Operand:
| 3 |
| 3 |

Operator: 3 * 3
| 9 |

Ans: 9
```

=== Complexity
* Time: O(n). n=number of characters in input
* Space: O(m). m continious operands


=== Code
==== CPP98
```cpp
class Solution {
public:
    int evalRPN(vector<string>& tokens) {
        
        stack<long> s;
        
        for (int i=0;i<tokens.size();++i) {
            if (tokens[i].size() == 1 && !isdigit(tokens[i][0])){
                long top1 = s.top(); s.pop();
                long top2 = s.top(); s.pop();
                long val;
                switch(tokens[i][0]){
                    case '+':
                        val = top1 + top2;
                        break;
                    case '-':
                        val = top2 - top1;
                        break;
                    case '/':
                        val = top2 / top1;
                        break;
                    case '*':
                        val = top1 * top2;
                        break;
                }//switch
                s.push(val);                
            }
            else {
                long a;
                stringstream ss(tokens[i]);
                ss >> a;
                s.push(a);
            }
        }
        return s.top();
    }
};
```
==== CPP11
```cpp
class Solution {
public:
    int evalRPN(vector<string>& tokens) {
        
        stack<long> st;
        
		for_each(tokens.begin(), tokens.end(), [&](string str){
			char ch = str[0];
			if (str.size() == 1 && !isdigit(ch)) {
                long top1 = st.top(); st.pop();
                long top2 = st.top(); st.pop();
                long val = 0;
				if (ch == '+')
					val = top1 + top2;
				else if (ch == '-')
					val = top2 - top1;
				else if (ch == '/')
					val = top2 / top1;
				else
					val = top1 * top2;
				st.push(val);
			} else {
				// Convert to long and push
                long a;
                stringstream ss(str);
                ss >> a;
                st.push(a);
			}
		});
        return st.top();
    }
};
```
==== Rust
```rs
impl Solution {
    pub fn eval_rpn(tokens: Vec<String>) -> i32 {
        let mut st: Vec<i64> = Vec::new();

        for token in tokens.iter() {
            let ch = match token.chars().next() {
                Some(a) => a,
                None => 'a',
            };
            if token.len() == 1 && !ch.is_digit(10) {
                // Operator
                let mut top1 = 0;
                if let Some(a) = st.pop() {
                    top1 = a;
                }
                let mut top2 = 0;
                if let Some(a) = st.pop() {
                    top2 = a;
                }
                let val = match ch {
                    '+' => top2 + top1,
                    '-' => top2 - top1,
                    '/' => top2 / top1,
                    '*' => top2 * top1,
                    _ => 0,
                };
                st.push(val);
            } else {
                // Operand
                let operand: i64 = match token.parse() {
                    Ok(val) => val,
                    Err(_) => 0, // Handle parsing error, defaulting to 0 in this case
                };
                st.push(operand);                
            }
        }
        match st.last() {
            Some(last) => *last as i32,
            None => 0, // Handle the case where the stack is empty
        }        
    }
}
```
