:toc:
:toclevels: 6


== Generic / Named Lifetimes
```rs
//Compliation Error
fn largest(x:&str, y:&str) -> &str{
    if x.len() > y.len() {
        x
    } else {
        y
    }
}
fn main() {
    let s1 = String::from("h");
    let result;
    {
        let s2 = String::from("www");
        result = longest(&s1, &s2);
    }
    println!("The longest string is: {}", result);
}
$ cargo run                 //Compilation error
   Compiling 
error[E0106]: missing lifetime specifier
 --> src/test.rs:9:33
  |
9 | fn largest(x: &str, y: &str) -> &str {
  |               ----     ----     ^ expected named lifetime parameterr
```
=== Why Compilation Error?
* if the compiler is unable to infer the lifetimes, it will result in a compilation error.
* The longest() attempts to return a reference to the longer of two string slices (&str).
* problem arises because the lifetimes of s1 and s2 are different. s1 has a longer lifetime than s2 because it was declared outside the inner block. 
* when s2 goes out of scope at the end of the inner block, the reference to s2 becomes invalid, but result will hold reference of s2, which has already been deallocated.
* This results in a dangling reference, which is a memory safety violation.

=== Solution: Generic lifetime parameter `'a`
* To fix this issue, you need to specify lifetimes for the function parameters to ensure that the returned reference is valid for the appropriate duration
* Prefix every parameter with `'a`. Apostrophe a (`'a`) denotes reference has generic lifetime. This is also called _Lifetime Annotation Syntax_.

=== Fixed code
```rs
fn largest<'a>(x:&'a str, y:&'a str) -> &'a str{           //Need to declare generic lifetime parameters inside <> before parameter list.
    if x.len() > y.len() {
        x
    } else {
        y
    }
}
```

=== Function will return smaller of both lifetimes
```rs
fn main() {                           //Block-1
    let x = String::from("abcd");
    let result;
    {                                 //Block-2
        let y = String::from("xyz");
        result = largest(x, y);
    }
    println!("{}", result);           //Printing string which is out of scope
}
```
Compliation Error Why?
- largest() will return smaller lifetime from x and y. y has smaller lifetime(ie Block-2).
- largest() will return y, which goes out of scope and we try printing string which is out of scope

== Lifetime Elision
- The patterns programmed into Rust complier which applies lifetime rules in desired situtation.
- **Input lifetimes:** Lifetimes on function or method parameters.
- **Output Lifetimes:** lifetimes on return values.

=== 1. How compiler determines Lifetime
- Compiler uses 3 rules to figure out what lifetimes references have when there aren’t explicit annotations. If the compiler gets to the end of the three rules and there are still references for which it can’t figure out lifetimes, the compiler will stop with an error.
- _Rule-1:_ Each parameter that is a reference gets its own lifetime parameter. 
```rs
fn longest<'a, 'b>(x: &'a str, y: &'b str) -> &str {
```
- _Rule-2:_ if there is exactly one input lifetime parameter, that lifetime is assigned to all output lifetime parameters.
```rs
fn foo<'a>(x: &'a i32) -> &'a i32.
```
- _Rule-3:_ If there are multiple input lifetime parameters, but one of them is `&self` or `&mut self`, the lifetime of self is assigned to all output lifetime parameters.

== Lifetime variables for structs
```rs
struct test<'a> {                       //struct having 1 member having lifetime
    part: &'a str,
}
impl<'a> test<'a> {                     //impl need to be declared with lifetime var,
    fn fun(&self) -> i32 {
        3
    }
}
```

=== Static lifetime
- This reference can live for the entire duration of the program. All string literals have the 'static lifetime. 
- The text of this string is stored directly in the program’s binary, which is always available
```rs
let s: &'static str = "test";
```
