:toc:
:toclevels: 6

== Install & Run (Vite app=React)
=== Install node and vscode
```c
Install nodejs: https://nodejs.org/en/download
C:\Users\amitk>node -v
v20.9.0

Code Editor(VSCode): Extension: Prettier Code format extension
```
=== Run vite app 
```c
C:\Users\amitk\source\repos\React>npm create vite@4.1.0
Need to install the following packages:
create-vite@4.1.0
Ok to proceed? (y)
√ Project name: ... react-app
√ Select a framework: » React
√ Select a variant: » TypeScript

Scaffolding project in C:\Users\amitk\source\repos\React\react-app...

Done. Now run:

  cd react-app
  npm install
  npm run dev
C:\Users\amitk\source\repos\React\react-app> npm install
C:\Users\amitk\source\repos\React\react-app> npm run dev
VITE v4.5.0  ready in 2441 ms
  ➜  Local:   http://localhost:5173/
```

=== Folder walkthru
```c
|
|-- node_modules: All 3rd party libraries exist (donot touch)
|-- public: Contains public facing images,video files etc
|-- src: This is src folder of our application. Application has 1 component called App component.
      |- App.js
index.html: We have <div id="root"></div>. This is container for application
tsconfig.js: Typescript setting file. Tells compiler how to compile typescript code to javascript
vite.config.js: Config file for vite
```

== Creating Components
=== Virtual DOM
* When Application starts React takes this component Tree and build a Virtual DOM(a javascript datastructure)
** Virtual DOM: This is lightweight in memory representation of Component tree. Updating DOM on changing compoent tree is Done by React DOM

=== 1. Create Message-Component(Hello World)
* We will build a Component Tree, where
** App(root component)
** Message(child Component)

*Component Tree*
```mermaid
classDiagram
    class App["App Component"]
    class Message["Message Component(Hello World)"]
    App --> Message
```

*Virtual DOM*
```mermaid
classDiagram
    class div["div"]
    class h1["h1"]
    div --> h1
```
* 1. Create new file Message.tsx(Typescript file) in src folder
```c
//src/Message.tsx
// Follow CamelCase (also called Pascal Case)

//1. Create Function based React component.
function Message() {
    //This is syntax of JSX(Javascript XML code)
    //Under the hood, it will get converted to Javascript code
    //React.createElement("h1", null, "Hello World");
    return <h1>Hello World</h1>;
}

//2. To use above created component
// we need to export it as Default created Object
export default Message;
```
* 2. src\App.tsx. Delete everything from file and start afresh
```c
//Steps 1,2 are in src/Message.tsx file

// import Message component
import Message from "./Message";

//3. Create a Component called App, which contains <div>
// <div> calls other components
function App() {
  //4. Message component is used as regular HTML components.
  // We need to close the imported component
  return <div><Message></Message></div>;
}

// 5. Export App component(as default) from this class
// so that it can be used somewhere else
export default App;
```
* 3. npm run dev
```c
http://localhost:5173/
```

=== 2. Create Basic ListGroup
==== a. Use link:https://getbootstrap.com/[bootstrap]
bootstrap is css library, which gives classes to applications to style their applications.
```js
PS C:\Users\amitk\source\repos\React\react-app> npm i bootstrap@5.2.3

changed 24 packages, and audited 79 packages in 7s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
* b. Use bootstrap.css
** Delete every thing from src\App.css
** Delete src\index.css completely
** Provide path of bootstrap.css in src\main.tsx
```
//import './index.css'                        << Remove this
import 'bootstrap/dist/css/bootstrap.css'    //Insert this
```

==== b. Create component
* 1. Create a folder `components` inside src. We will place all our components in this folder.
```js
src
|-components
  |-ListGroup.tsx
```
* 2. Take list group code from here: link:https://getbootstrap.com/docs/5.3/components/list-group/[List Group].
** Replace class with className.
```c
//1. Create Function based React component.

function ListGroup() {
    //This is syntax of JSX(Javascript XML code)
  return (
    <ul className="list-group">
      <li className="list-group-item">An item</li>
      <li className="list-group-item">A second item</li>
      <li className="list-group-item">A third item</li>
      <li className="list-group-item">A fourth item</li>
      <li className="list-group-item">And a fifth one</li>
    </ul>
  );
}

//2. To use above created component
// we need to export it as Default created Object
export default ListGroup;
```
* 2. src\App.tsx. Delete everything from file and start afresh
```c
//Steps 1,2 are in src/components/Listgruop.tsx file

// import Listgruop component
import Listgruop from "./components/Listgruop";

//3. Create a Component called App, which contains <div>
// <div> calls other components
function App() {
  //4. Message component is used as regular HTML components.
  // We need to close the imported component
  return <div><Listgruop></Listgruop></div>;
}

// 5. Export App component(as default) from this class
// so that it can be used somewhere else
export default App;
```
