:toc:
:toclevels: 6


== React
* React is a JavaScript library for rendering user interfaces (UI). UI is built from small units like buttons, text, and images.
* React lets you combine them into reusable, nestable components.

== Features
=== Add components to Page
==== 1. Button
* React apps are made out of components. A component is a piece of the UI (user interface) that has its own logic and appearance. A component can be as small as a button, or as large as an entire page.
* React components are JavaScript functions that return markup
* Now that you’ve declared MyButton, you can nest it into another component.  React component names must always start with a capital letter.
```js
// 1. Declare a React component. This is React component. React components are JavaScript functions that return markup.
function MyButton() {
  return (
    <button>
      I'm a button
    </button>
  );
}

// 2. Nest it into another component.
export default function MyApp() {    //export default keywords specify the main component in the file
  return (
    <div>
      <h1>Welcome to my app</h1>
      <MyButton />
    </div>
  );
}
```

==== 2. Image
```js
<img className="avatar" />

// Then you write the CSS rules for it in a separate CSS file
.avatar {
  border-radius: 50%;
}
```

=== Conditions
==== 1. if else
```js
let content;
if (isLoggedIn) {
  content = <AdminPanel />;
} else {
  content = <LoginForm />;
}
return (
  <div>
    {content}
  </div>
);
```

=== Event Handling / Counting
==== 1. Button click
```js
function MyButton() {
  function handleClick() {
    alert('You clicked me!');
  }

  return (
    <button onClick={handleClick}>
      Click me
    </button>
  );
}
```

==== 2. Count number of time button clicked (Add state to your component)
```js
import { useState } from 'react';
function MyButton() {
  const [count, setCount] = useState(0);    //Declare a state variable inside your component
  // ...
  function handleClick() {
    setCount(count + 1);
  }

  return (
    <button onClick={handleClick}>
      Clicked {count} times
    </button>
  );
}
```

=== Hooks
Functions starting with use are called Hooks. useState is a built-in Hook provided by React. 

== link:https://create-react-app.dev/docs/getting-started/[Create React App]
```c
npx create-react-app my-app
cd my-app
npm start
open http://localhost:3000/ to see your app.
```

== React Element
=== Render element to DOM
```js
var ch1 = React.createElement("h1", null, "Chapter-1")                          //1: Create element without properties
var ch2 = React.createElement("h1", {id:"t", 'data-type:"title"}, "Chapter-2")  //2: Create element with properties
//h1=Type of element. Heading element
//id,data-type: These are properties of element
//Chapter-1=element's children

During rendering react will convert this to actual DOM object.
<h1 >Chapter-1" </h1>
<h1 data-reactroot id="t" data-type="title"> Chapter-2 </h1>    //data-reactroot will always appear as an attribute of the root element.

ReactDOM.render(ch1, document.getElementById('react-container'))    //3. Render element to DOM

<body>
 <div id="react-container">
 <h1>Chapter-1</h1>
 </div>
</body>
```

=== pros.children
data-reactroot: This is tree's root
```js
React.createElement(
 "parent",                                  //This is root element
 null,
 React.createElement("li", null, "child1"), //These are 3 children
 React.createElement("li", null, "child2"),
 React.createElement("li", null, "child3"),
)

arr[] = [child1, child2, child3]          //React creates an array of these child elements and sets the value of props.children to that array.
pros.children = arr
```

== Libraries
=== 1. React library
To create views. 

=== 2. ReactDOM library
To render the UI in the browser.
