:toc:
:toclevels: 6

== link:https://code-with-amitk.github.io/Networking/OSI-Layers/[SSL/TLS]
* SSL vs TLS
* NSS(TLS Implementation) vs Openssl

== SSL Client, Server
- link:Certificates.adoc#certificate-example[Certificate]

**Flow**

- client, server provides public key+CSK to CA and get their Certificate + CA Cert respectively
- Server sends its certificate to client in Server Hello. Client verifies the server cert using link:https://code-with-amitk.github.io/Networking/OSI-Layers/Layer-3/Security/Signing.html[Digital Signature] in Certificate
- Client generates a random Pre-Master Secret(PMS), encrypts it with the Server's public key(which is present in Certificate), and sends it to the server.
- Server decrypts the Message using its own Pvt key and gets PMS key
- Client and server both independently calculate Master Key using Mater key = PRF(PMS+RNc, RNs). Note (RNc, RNs) are exchanged in Client Hello, Server Hello
- Using Master key, Both client and server derive their 2 session keys. Session Key client(SKc), Session Key server(SKs). When sending data client encrypts using SKs and viceversa.

```
Pre-Master Secret = ABC
Client Random     = 123
Server Random     = XYZ

ABC + 123 + XYZ
        ↓
  Master Secret
        ↓
    KDF / PRF
     ↙       ↘
Session Key   Session Key
client        server
```

```mermaid
sequenceDiagram
    participant CA as Root/Intermediate CA
    participant C as TLS Client / Browser
    participant S as TLS Server

    rect rgb(220,255,220)
        Note over C: Generate Public, Pvt key
        C->>CA: CSR + Client Public Key
        CA-->>C: Client Certificate + CA Certificate

        Note over S: Generate Public, Pvt key
        S->>CA: CSR + Server Public Key
        CA-->>S: Server Certificate + CA Certificate
    end

    Note over C: Browser trusts Root CA<br/>Root CA certificate added to trust store

    rect rgb(255,220,235)
        C->>S: TCP SYN
        S->>C: SYN + ACK
        C->>S: ACK
    end

    rect rgb(200,225,255)
        C->>S: ClientHello<br/>TLS version + Cipher Suites + RNc
        S->>C: ServerHello<br/>Selected Cipher Suite + RNs

        S->>C: Server Certificate<br/>Server Certificate Chain
        S->>C: ServerKeyExchange (if required)
        S->>C: CertificateRequest (optional - mTLS)
        S->>C: ServerHelloDone
    end

    rect rgb(230,230,230)
        Note over C: Validate Certificate Chain
        Note over C: Check issuer, validity period,<br/>hostname/SAN, Key Usage/EKU

        Note over C: Validate Server Cert<br>Retrieve same RootCA.crt from DB<br>Gets Public Key from RootCA.crt stored in DB<br>Verify [Digital Signature] present on server.crt<br><br>Decrypt DS of received server.crt using Public key of CA=Hash<br>server.crt > [sha256] > Hash<br>if Hash Match. Good

    end

    alt mTLS requested
        C->>S: Client Certificate
        Note over S: Validate Client Certificate
        C->>S: CertificateVerify
        Note over S: Verify Client signature
    end

    C->>S: ClientKeyExchange<br/>Encrypted Pre-Master Secret

    Note over C: Client generates <br>Random Pre-Master Secret(PMS)<br><br>Encrypt using Server's Public Key

    C->>S: Encrypted(Pre Master Secret(PMS) Key)
    Note over S: Decrypt (PMS) using Self Private Key

    Note over C: Calculate<br>Master key = PRF(PMS, RNc, RNs)<br><br>RNs sent in Server Hello
    Note over S: Calculate<br>Master key = PRF(PMS, RNc, RNs)<br><br>RNc sent in Client Hello

    Note over C: Calculate<br>Session keys from Master key<br><br>SKc(Session key client),<br>SKs(Session key server)
    Note over S: Calculate<br>Session keys from Master key<br><br>SKc(Session key client),<br>SKs(Session key server)

    C->>S: ChangeCipherSpec
    S->>C: ChangeCipherSpec

    rect rgb(200,225,255)
        Note over C,S: TLS Record Protocol

        C->>S: Encrypt SKc(Data)
        Note over S: Server has derived SKc<br>It decrypts using SKc
        S->>C: Encrypt SKs(Data)

    end
```

===== ALERT-PROTOCOL
* Mechanism to inform other end that some thing wrong happened(either in handshake, record protocol). This message consists of two fields. (Alert Message,Criticality of the alert).

== Decrypting Traffic in Wireshark
=== link:https://techzone.cisco.com/t5/Troubleshooting-and-Tools/How-to-Decrypt-SSL-traffic-using-Wireshark/ta-p/355403[1. SSL Traffic]
* Get a. Server's: RSA pvt key,  b. Clients's: Pre-master-secret for each session
* Enter the key in: Wireshark Menu -> Edit -> Prefrences -> Protocol -> ssl -> RSA Key List

=== link:https://wiki.wireshark.org/Kerberos[2. Decrypt GSS-API]
* 1. Get keytab for Administrator user from AD
```c
//Generate keytab
PS C:\Users\Administrator> ktpass /princ Administrator@test.com /pass Password /crypto RC4-HMAC-NT /ptype KRB5_NT_PRINCIPAL /out test.keytab

//Check keytab is valid
PS C:\Users\Administrator> klist
```
* 2. wireshark > Edit > Preferences > Protocols > Krb5 > Place keytab > Ok
* 3. Encypted GSS-API payload will appear decrypted now.

== DTLS / Datagram TLS (TLS over UDP)
* DTLS is port of TLS over UDP.
* Why UDP?
  - Less Delay(Good Choice for Audio/Video)
  - No retransmissions (for lost packets)
  - No Connection Setup (Handshakes)
  - For Multicast, UDP is used
  - If TCP is used sender has to take care of Each recipient's receiving rate
  - Packet Header of UDP(8bytes) is much smaller than TCP(20 bytes)
WHICH PACKET IS DELIVERED RELIABLY IN DTLS?
