:toc:
:toclevels:6


== link:[HTTP Cookie / Web cookie / Internet cookie / browser cookie](https://code-with-amitk.github.io/Networking/OSI-Layers/Layer-7/HTTP/)
* What is cookie?
* Why cookie?
* Storage Example on browser
* Terms(Stolen Cookie, Cookie Surrogate)

== Inbound, Outbound Requests
* inbound means "toward the origin server"
* outbound means "toward the user agent".

== Origin Server
Program that can provide authoritative responses to HTTP client

== PAC(proxy auto-configuration) File
* This is a Javascript file that instructs a browser to forward traffic to a particular link:/System-Design/Concepts/Proxy_Servers[proxy server], instead of directly to the destination server. All browsers support PAC File.
* This configures link:/System-Design/Concepts/Proxy_Servers/#exp[Explicit Proxy] in browser.

=== Limitations of PAC
* Can only send web traffic, not other(eg: video, audio).
* Admin user can change proxy address(to which requests need to go) in PAC. Also admin can completely disable it.
```c
//Example of PAC File
function FindProxyForURL(url, host) {

// If the hostname matches, send direct.
	if (dnsDomainIs(host, "intranet.domain.com"))
		return "DIRECT";

// If the protocol or URL matches, send direct.
	if (url.substring(0, 4)=="ftp:")
		return "DIRECT";

// If the requested website is hosted within the internal network, send direct.
	if (isPlainHostName(host) ||
		isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0") ||
		isInNet(dnsResolve(host), "172.16.0.0",  "255.240.0.0") ||
		isInNet(dnsResolve(host), "192.168.0.0",  "255.255.0.0") ||
		isInNet(dnsResolve(host), "127.0.0.0", "255.255.255.0"))
		return "DIRECT";

// If the IP address of the local machine is within a defined
// subnet, send to a specific proxy.
	if (isInNet(myIpAddress(), "10.10.5.0", "255.255.255.0"))
		return "PROXY 1.2.3.4:8080";

// DEFAULT RULE: All other traffic, use below proxies, in fail-over order.
	return "PROXY 4.5.6.7:8080; PROXY 7.8.9.10:8080";

}
```

== User Agent
Any client programs that initiate a HTTP request.

== Intermediaries
```c
UA ======Proxy=====Tunnel======Reverse_Proxy====== OS
```

== Gateway (or Reverse Proxy)
- Acts as an [origin server](#os) for the outbound connection but translates received requests and forwards them inbound to another server or servers.

== Tunnel
- A blind relay between 2 connections without changing the messages.

