:toc:
:toclevels:6


== HTTP Cookie / Web cookie / Internet cookie / browser cookie
=== What is cookie?
Web Server asks web browser to store some information on user's PC. Information is stored in a file(called Cookie) _created by Web browser_ & placed on the user's computer.

=== Why cookie?
* To track the user's browsing activity(clicking particular buttons, recording which pages were visited in the past, User Preferences).
* Saving info user entered in forms: names, addresses, passwords(stored as hashed), and payment card numbers.
```c
  Web Browser                                   Web server
         -- GET /sample_page.html HTTP/2.0 ->
            Host: www.example.org
	    
         <------- HTTP/2.0 200 OK---------------
                 Content-Type: text/html
                 Set-Cookie: yummy_cookie=choco       //Store cookie
                 Set-Cookie: tasty_cookie=strawberry
                 [page content]
		 
 store information
 in Cookie file
```
=== Example?
```c
* _Path:_ "C:\Users\user_name\AppData\Local\Google\Chrome\User Data\Default\Network\Cookie(SQL Lite DB)"
* _In Browser:_ Right-click on your browser window > Inspect > Applications tab > Cookies > Check installed cookies
# cat "C:\Users\user_name\AppData\Local\Google\Chrome\User Data\Default\Network\Cookie"
cookie_name      cookie_value				domain			valid_timestamp			cookie_len	cookie_priority
cookie_1	lwyMCcUDlsziLcAF/AOF3W1gCBO1aeb291	.google.com	/	2024-10-09T14:58:52.469Z	51			High
```
cookie_value is application specific and only server side application understand it

=== Stolen Cookie? 
* If hacker steals and installs your cookies into their web browser, hacker will get access your account.
* _How cookie theaft can be avoided?_ Cleaning cookies every 7-14 days.

== Inbound, Outbound Requests
* inbound means "toward the origin server"
* outbound means "toward the user agent".

== Origin Server
Program that can provide authoritative responses to HTTP client

== PAC(proxy auto-configuration) File
* This is a Javascript file that instructs a browser to forward traffic to a particular link:/System-Design/Concepts/Proxy_Servers[proxy server], instead of directly to the destination server. All browsers support PAC File.
* This configures link:/System-Design/Concepts/Proxy_Servers/#exp[Explicit Proxy] in browser.

=== Limitations of PAC
* Can only send web traffic, not other(eg: video, audio).
* Admin user can change proxy address(to which requests need to go) in PAC. Also admin can completely disable it.
```c
//Example of PAC File
function FindProxyForURL(url, host) {

// If the hostname matches, send direct.
	if (dnsDomainIs(host, "intranet.domain.com"))
		return "DIRECT";

// If the protocol or URL matches, send direct.
	if (url.substring(0, 4)=="ftp:")
		return "DIRECT";

// If the requested website is hosted within the internal network, send direct.
	if (isPlainHostName(host) ||
		isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0") ||
		isInNet(dnsResolve(host), "172.16.0.0",  "255.240.0.0") ||
		isInNet(dnsResolve(host), "192.168.0.0",  "255.255.0.0") ||
		isInNet(dnsResolve(host), "127.0.0.0", "255.255.255.0"))
		return "DIRECT";

// If the IP address of the local machine is within a defined
// subnet, send to a specific proxy.
	if (isInNet(myIpAddress(), "10.10.5.0", "255.255.255.0"))
		return "PROXY 1.2.3.4:8080";

// DEFAULT RULE: All other traffic, use below proxies, in fail-over order.
	return "PROXY 4.5.6.7:8080; PROXY 7.8.9.10:8080";

}
```

== User Agent
Any client programs that initiate a HTTP request.

== Intermediaries
```c
UA ======Proxy=====Tunnel======Reverse_Proxy====== OS
```

== Gateway (or Reverse Proxy)
- Acts as an [origin server](#os) for the outbound connection but translates received requests and forwards them inbound to another server or servers.

== Tunnel
- A blind relay between 2 connections without changing the messages.

