:toc:
:toclevels: 6

== link:https://leetcode.com/problems/find-in-mountain-array/[1095. Find in Mountain Array]
You may recall that an array arr is a mountain array if and only if:

arr.length >= 3
There exists some i with 0 < i < arr.length - 1 such that:
arr[0] < arr[1] < ... < arr[i - 1] < arr[i]
arr[i] > arr[i + 1] > ... > arr[arr.length - 1]
Given a mountain array mountainArr, return the minimum index such that mountainArr.get(index) == target. If such an index does not exist, return -1.

You cannot access the mountain array directly. You may only access the array using a MountainArray interface:

MountainArray.get(k) returns the element of the array at index k (0-indexed).
MountainArray.length() returns the length of the array.
*Submissions making more than 100 calls to MountainArray.get* will be judged Wrong Answer. Also, any solutions that attempt to circumvent the judge will result in disqualification.
```c
 Example 1:
Input: array = [1,2,3,4,5,3,1], target = 3
Output: 2
Explanation: 3 exists in the array, at index=2 and index=5. Return the minimum index, which is 2.
```

== Approach-1. Linear Search. TLE
=== Code
```cpp
/**
 * // This is the MountainArray's API interface.
 * // You should not implement it, or speculate about its implementation
 * class MountainArray {
 *   public:
 *     int get(int index);
 *     int length();
 * };
 */

class Solution {
public:
    int findInMountainArray(int target, MountainArray &mountainArr) {
        int len = mountainArr.length();
        for (int i=0;i<len;++i) {
            if (target == mountainArr.get(i))
                return i;
        }
        return -1;
    }
};
```

== Approach-2. Binary Search
=== Logic
* Find peak point using binary search
* Then 1st search target in left array of peak. If element is found return index.
* if target is not found in left array, then search in right, if element is found return index
* if element is not found in either left or right of peak, return -1.

=== Complexity
* Time: O(logn). Search Peak, Search element in left arr of peak, search element in right array of peak
* Space: O(1)

=== Code
==== CPP
```cpp
/**
 * // This is the MountainArray's API interface.
 * // You should not implement it, or speculate about its implementation
 * class MountainArray {
 *   public:
 *     int get(int index);
 *     int length();
 * };
 */

class Solution {
public:
    int findMountainPeak(MountainArray &mountainArr, int n) {
        int left = 0, right = n - 1;
        while (left < right) {
            int mid = left + (right - left) / 2;
            int midVal = mountainArr.get(mid);
            int midRightVal = mountainArr.get(mid + 1);
            if (midVal < midRightVal) {
                left = mid + 1;
            } else {
                right = mid;
            }
        }
        return left; // or right, they are equal at this point
    }
    int findInMountainArray(int target, MountainArray &mountainArr) {
        int n = mountainArr.length();
        int peak = findMountainPeak(mountainArr, n);
        
        // Search in the left of the peak
        int left = 0, right = peak;
        while (left <= right) {
            int mid = left + (right - left) / 2;
            int midVal = mountainArr.get(mid);
            if (midVal == target) {
                return mid;
            } else if (midVal < target) {
                left = mid + 1;
            } else {
                right = mid - 1;
            }
        }
        
        // Search in the right of the peak
        left = peak + 1, right = n - 1;
        while (left <= right) {
            int mid = left + (right - left) / 2;
            int midVal = mountainArr.get(mid);
            if (midVal == target) {
                return mid;
            } else if (midVal < target) {
                right = mid - 1;
            } else {
                left = mid + 1;
            }
        }
        
        return -1; // Target not found
    }
};
```
