:toc:
:toclevels: 6


== Yelp/Proximity Server/Nearby Recommendation System
* What? Used to discover nearby places(eg: schools near me), events, restaurants, theaters, etc.
* Yelp App on phone sends `(lattitude,longitude)` of user's device and yelp server sends locations within `10 km` radius of `(lattitude,longitude)` to the user.
  - (lattitude,longitude) are like coordinates of point on earth.

== 1. Requirements
=== Functional
> CRUD(Create=POST, Read=GET, Update=PUT, Delete=DELETE)
[[req-1]]
1. Add places  //POST
[[req-2]]
2. Update Places
[[req-3]]
3. Delete places
[[req-4]]
4. Given `(longitude,lattitude)` nearby places should be listed for given radius.  //GET
[[req-5]]
5. Users should be able to give reviews, ratings, open/close times, pictures etc.    //POST

== 2. BOE
* Storage Estimates:
```c
  - 200M~300M business listings are present on google
  - Each place {string name, string address, double lat, double long, `vector<string> reviews`, string photos_url}  = 2000 KB
  - 300M * 2000k = 60 PB / year
  - User Reviews,Photos,Videos will keep on increasing. Suppose becomes 5 times per year.  300PB
  - New Businesses also gets added, old fade away. Suppose from last year it becomes twice.  120PB
  500 PB/year
  5 years = 2 Exabytes
```
* QPS
```c
Assuming 100k user are accessing per sec
This may increase in peak season, and may decline/remain steady other times
```
* Bandwidth Estimates
```c
  - 100k req/s.
  - 1 GET request = 2KB
  - 1 UPDATE request = 4KB  //Avg of 2=3KB

  Incoming bytes = 100k x 3k = 300MBytes/sec
  Outgoing bytes = 100k x (sizeof 1 listing) = 100k x 2000 KB(calculated above) = 20GB/sec
```
  
== 3. System APIs
* 1. <<req-1, add_place>>. HTTP POST
```c
  POST https://url/v1/add_place
  header {
    Authorization: {Bearer "API_KEY_TOKEN"},
    lat: "",
    longitude: ""
  }
  body {
    name, description, picture_url, video_url
  }
```

* 2. <<req-2, update_place>>  //Update. HTTP PUT   Place/person/thing information
```c
  GET https://url/v1/search_place
  header {
    Authorization: {Bearer "API_KEY_TOKEN"},
    sort: optional,
    business-id: id    //unique key
  }
  body {              //Server will compare the data and update the changed
    name, description, picture_url, video_url,
    userLocation {
      lat: "",
      long: "",
    },
  }
```

* 4. <<req-4, search_place>>  //HTTP GET.     Place/person/thing information
```c
  GET https://url/v1/search_place
  header {
    Authorization: {Bearer "API_KEY_TOKEN"},
    userLocation {
      lat: "",
      long: "",
    },
    radius: 10km,  //default
    sort: optional,
    category: optional
  }
  //Returns json:
  {
    {            //business-1
      name: business-name
      photo: photo_url,
      ratings: array<ratings>,
      open close time: string
    },
    {
      //business-2
    },
  }
```

== 4. DATABASE
* Following are entities in system: Place, Place_Owner(who adds entry), Reviews, Photos, Videos

* 1. Place table
link:/System-Design/Concepts/Databases/Indexing[indexing for faster searching]
```c
| ownerID(fk)[indexed] | lattitude | longitude | placeID(pk) | Description | Category | lastupdated_timestamp[indexed] |

ownerID: id of person who created the entry
lattitude: Geographic coordinate specifying north–south position of a point on the Earth's surface.
longitude: Geographic coordinate specifying east–west position of a point on the Earth's surface.  
  - (lattitude, longitude): precise location of features on the surface of the Earth.
placeID(8 bytes): Uniquely identifies a location. LocationId is taken 8 bytes(64 bits) considering future in mind.
  - 2<sup>64</sup> = Huge number of locations
Description(512 bytes)
Category(1 byte): E.g., coffee shop, restaurant, theater, etc.
```

* 2. Place_owner table
```c
| ownerID(pk) | name | email | secret_key | placeID(fk) | created_timestamp |

placeId: locations this owner owns
created_timestamp: profile created by owner at this time
```

* 3. Reviews table
```c
| review_id(pk) | creator_name | creator_email | review_description | placeID(fk) | created_timestamp |
```

* 4. Place Photo table
** link:/System-Design/Concepts/Databases/README.adoc#object-vs-block-vs-file-storage[photos stored on object store]
```c
| photo_id(pk) | active | photo_url | placeID(fk) | created_timestamp | marked_inactive_timestamp |

active: Is photo active on website, ie getting displayed. We will remove photo from db
  after 30 days, if marks inactive
photo_url: 
```

* 5. Place video table
** link:/System-Design/Concepts/Databases/README.adoc#object-vs-block-vs-file-storage[Videos stored on object store]

* 6. Reviews table
** link:/System-Design/Concepts/Databases/README.adoc#object-vs-block-vs-file-storage[Review stored on object store]
```c
| reviewId(pk) | review-text-url | placeid(fk) | stars |
```

### 5B. DATA PARTIONING
#### 5B1. SHARDING BASED ON REGION
  - Storing all places having particular zip code on set of servers.
  - Over time, some regions can end up storing a lot of places compared to others
#### 5B1. SHARDING BASED ON LOCATION ID
  - Using locationID to hash function. ServerID is generated. Data will be stored here.

== 5. HLD
- Information of places to be stored in **SQL DB** and databases are arranged in **[Quad Tree format](/DS_Questions/Data_Structures/Trees/M-Ary_Trees/Quad_Tree/)** for searching faster.
- Whole whole world map is divided into **grids**. Grids will have coordinates(ie location of places). SQL DB will store information of grids. 1 grid can reside on multiple servers.
```c
Quad Tree 
           [root]
          / | \ \

  struct gridNode_or_dbNode {
    uint32 gridId_or_dbID;            //gridId hash gives the DB where (latt-start,long-start,latt-end,long-end) are stored
    double lattitude-start,lattitude-end;
    double longitude-start,longitude-end;
    struct grid *child[4];
  }  
```
- ***Case-1: User queries `Hotels near me`***
  - User's device provides self (lattitude,longitude). Search is started from `[root]` node of quadTree & based on (start,end) lat, long stored, query is passed to appropriate child
```c
(lat, lon) => (lattitude, longitude)

    User
  Schools near me
1. Google-map sends self
  (lat,lon) --->  CDN
               if info is not stale
               return, redirect to
        <----- approapriate Datacenter

  1. User
  (lat,lon)     <---------------- Data center ----------------------------------------------------------->
      ------>    LB     2. APP-SERVER
                  -----> lat,lon 
                        Create transaction_id(tid),
                        get token     ---org secret-->  IAM(provides validation tokens)
                                      <---------------
                        Send on kafka
                        (lat,lon,tid,token,topic=xx)
                                -----------------> Kafka

                        4. DB-SEARCHER <---------------
                        (subscribed to topic=xx)
                        verifies token ---------------------> IAM
                                       <------------------------
                         Creates dbID of quadtree(root)
                         yy->|Hash|->x
                          ---- search in db(id=x)(lat,lon) -->  QUADTREE(root) //DBs arranged in quadtree format
                                                                jump to appropriate child
                                                                   Lat_endchild1 < lat && Lon_endchild1 < lon
                         DB-SEARCHER <---- gridId of child-2 ----  Look at child-2
                         gridId-child1->|Hash|->yy
                                  --- search in db=yy (lat,lon) ->  child-2
                                  <---- gridId of child-10 ----     Look at child-10
                         gridId-child10->|Hash|->zz
                                  --- search in db=zz (lat,lon) ->  child-10
                               <---- hotels in 10km of (lat,lon) -------
                          Create json
                          (json,transaction_id)----------------> Kafka
                          
                          5. SENDER uServer <-----------------------
                          Get user's hostname using tid
                          Send json(Hotels in 10km) to user
  6. User
       <--json(Hotels in 10km)--
```
  - ***GRID SIZE***: Dynamically adjust the grid size such that whenever grid gets lot of places(maybe > 500) break it down to create smaller grids.
    - So, whenever a grid reaches 500 things, ***break it down into four grids*** of equal size and distribute places among them.
      - Thickly populated areas like San Francisco will have a lot of grids.
      - Sparsely populated area like the Pacific Ocean will have large grids with places only around the coastal lines.
    - All the leaf nodes will represent the grids that cannot be further broken down
  - **Finding neighbouring grid of given grid***
    - Note only leaf node can contain list of locations
    - All leaf nodes of a parent will be neighbours. We can connect all leaves using `doubly linked list` and move easiy between them.
  - **MEMORY REQUIREMENTS**
    - Number of Grids
      - Total earth area = 200 * 10<sub>6</sub> sq miles. (200 Million sq miles)
      - let's take grid diagonal = 10 miles
      - Total Grids = 20 Million
    - objectId=4 bytes, lattitude,longitude=8bytes.   24 bytes
    - Database requirement:  24 * 20 * 10<sub>6</sub> = 4 * 10<sub>9</sub> = 4 GB
    - QuadTree: objectID(4 bytes) + 4 pointers(32 bytes) = 36 * 20 * 10<sub>6</sub> = 7 GB
  
  - ***Case-2: Storing Place/Thing information on QuadTree, SQL-DB***
```
User                            
click on add New place
- Fill category
- Pick place on map(Lattitude-n, Longitude-n)
- Add name of place
         Authentication-happened
-Add_Place(lattitude-n,long-n,category,name)   <-------------------Data center-------------------->
                            |-------------->  APP-SERVER    
                                     Search (lattitude-n,long-n) in QuadTree
                                                 |----(lattitude-n,long-n)---->   QUADTREE(root)
                                                 |                                 / | \ \
                                                 |                       lattitude-start < lattitude-n < lattitude-end
                                                 |                       longitude-start < longitude-n < longitude-end
                                                 |                        Node-89 will store lattitude-n,longitude-n
                                                 |  <--gridID of Node89---------------|
                                                 |
                                        gridId->|Hash|->ServerID(3)                  DB-1
                                                      DB-3 will store infor
                                                             ---information----->    DB-3
                                                                              objectID,lattitude,longitude,locationID
                                                                              Description,Category
 
```
   
  
## 6. REPLICATION
  - **QUad-tree** We will have replication of quad-tree in master-slave configuration 
    - Master: caters all writes. Syncs data to replica
    - Replica: Can serve Read traffic.
  - **Server dies**
    - We can have a secondary replica of each server and, if primary dies, it can take control after the failover. 
    - Both primary and secondary servers will have the same QuadTree structure.
    
## 7. CACHE(memcached)
  - To deal with hot Places, we can introduce a cache in front of our database.
  - Based on clients’ usage pattern, we can adjust how many cache servers we need.
  - Cache Eviction policy: LRU
  
## 8. LOAD BALANCING
  - At 2 places load balancers can be placed:
    a. Between clients and Application servers
    b. B/w application & backend servers.
    
## 9. RANKING
- **WHAT** rank the search results by proximity, popularity, relevance.
- **How**
  - Store the start given by user for place in QuadTree and database both.
  - While searching for the top 100 places in a given radius, we can ask each partition of the QuadTree to return the top 100 places with maximum popularity. 
  - Assuming the popularity of a place is not expected to reflect in the system within a few hours, we can decide to update it once or twice a day, especially when the load on the system is minimum
