:toc:
:toclevels: 6

== link:https://leetcode.com/problems/insert-interval/description/[57. Insert Interval]
You are given an array of non-overlapping intervals intervals where intervals[i] = [starti, endi] represent the start and the end of the ith interval and intervals is sorted in ascending order by starti. You are also given an interval newInterval = [start, end] that represents the start and end of another interval.

Insert newInterval into intervals such that intervals is still sorted in ascending order by starti and intervals still does not have any overlapping intervals (merge overlapping intervals if necessary).

Return intervals after the insertion.

Note that you don't need to modify intervals in-place. You can make a new array and return it.
```c
Example 1:
Input: intervals = [[1,3],[6,9]], newInterval = [2,5]
Output: [[1,5],[6,9]]

Example 2:
Input: intervals = [[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval = [4,8]
Output: [[1,2],[3,10],[12,16]]
Explanation: Because the new interval [4,8] overlaps with [3,5],[6,7],[8,10].
```

== Approach-1. O(n)
=== Logic
```c
intervals = [[1,2],[3,5],[6,7],[8,10],[12,16]]
newInterval = [4,8]


```
* Iterate through input intervals arrays. Take new_start = newInterval[0], new_end = newInterval[1]
* non-overlapping intervals: Interval which fall outside newInterval range. Insert intervals as such in output array
```c
[1,2]    //present_start=1, present_end=2
newInterval = [4,8]
  if (present_end < new_start || present_start > new_end)
```
* overlapping intervals: 
```c
    -------------------------------
    1  2  3  4  5  6  7  8
          |-----|
             |-----------|
[3,5]
newInterval = [4,8]

start=min(both starts).  min(3,4)  = 3
end= max(e, end).        max(5,8)  = 8
```

=== Complexity
* Time: O(n)
* Space: O(n)

=== Code
==== CPP
```cpp
class Solution {
    using vvI = vector<vector<int>>;
    using vI = vector<int>;
public:
    vector<vector<int>> insert(vector<vector<int>>& intervals, vector<int>& newInterval) {
        vvI out;
        vI temp;
        int new_start = newInterval[0], new_end = newInterval[1];
        int s = new_start, e = new_end;
        bool inserted = false; // to track if newInterval has been inserted
        for (const auto& i : intervals) {
            int start = i[0], end = i[1];
            if (end < new_start || start > new_end) { // non-overlapping intervals
                if (!inserted && start > new_end) { // newInterval should be inserted here
                    temp = {s, e};
                    out.push_back(temp);
                    inserted = true;
                }
                out.push_back(i);
            } else { // overlapping intervals
                s = min(s, start); // update start point
                e = max(e, end);   // update end point
            }
        }
        if (!inserted) { // newInterval should be inserted at the end
            temp = {s, e};
            out.push_back(temp);
        }
        return out;
    }
};
```
