:toc:
:toclevels: 6

== link:https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/[452. Minimum Number of Arrows to Burst Balloons]
There are some spherical balloons taped onto a flat wall that represents the XY-plane. The balloons are represented as a 2D integer array points where points[i] = [xstart, xend] denotes a balloon whose horizontal diameter stretches between xstart and xend. You do not know the exact y-coordinates of the balloons.

Arrows can be shot up directly vertically (in the positive y-direction) from different points along the x-axis. A balloon with xstart and xend is burst by an arrow shot at x if xstart <= x <= xend. There is no limit to the number of arrows that can be shot. A shot arrow keeps traveling up infinitely, bursting any balloons in its path.

Given the array points, return the minimum number of arrows that must be shot to burst all balloons.

```c
Example 1:
Input: points = [[10,16],[2,8],[1,6],[7,12]]
Output: 2
Explanation: The balloons can be burst by 2 arrows:
- Shoot an arrow at x = 6, bursting the balloons [2,8] and [1,6].
- Shoot an arrow at x = 11, bursting the balloons [10,16] and [7,12].

Example 2:
Input: points = [[1,2],[3,4],[5,6],[7,8]]
Output: 4
Explanation: One arrow needs to be shot for each balloon for a total of 4 arrows.

Example 3:
Input: points = [[1,2],[2,3],[3,4],[4,5]]
Output: 2
Explanation: The balloons can be burst by 2 arrows:
- Shoot an arrow at x = 2, bursting the balloons [1,2] and [2,3].
- Shoot an arrow at x = 4, bursting the balloons [3,4] and [4,5].
```

== Approach-1. O(nlogn). Sort
=== Logic
* sort the input vector.
```c
input = [[10,16],[2,8],[1,6],[7,12]]
sort  = [1,6][2,8][7,12][10,16]

  
  1 ---------- 6
     2---------|-----8
               |  7----------12
               |         10-----------16
               |          |
            arrow-1      arrow2 
```
* Find the last endpoint for a ballon which overlaps with other ballons. Bcoz that is the point where arrow hit will burst both the ballons.
```c
  (1,6) (2,8) (7,12) (10,16)
     |
    end

if (next[0] > end)  //2>8
  that means 1 arrow will not suffice to burst both ballons
  arrows++
else //next[0]<end  
  We can burst both of these ballons with 1 arrow
```

=== Complexity
* Time: O(n)
* Space: O(1)

=== Code
==== CPP
```cpp
class Solution {
public:
    int findMinArrowShots(vector<vector<int>>& points) {
        std::sort(points.begin(), points.end(), [](const auto& a, const auto& b) {
            return a[0] < b[0];
            });

        int arrows = 1;
        int end = points[0][1];

        for (size_t i = 1; i < points.size(); ++i) {
            if (points[i][0] > end) {
                arrows++;
                end = points[i][1];
            }
            else {
                end = std::min(end, points[i][1]);
            }
        }
        return arrows;
    }
};
```
==== Rust
```rs
impl Solution {
    pub fn find_min_arrow_shots(points1: Vec<Vec<i32>>) -> i32 {
        // points1 is not mutable reference, hence we cannnot sort
        // the array. Hence we need to create a mutable copy of vector
        let mut points:Vec<Vec<i32>> = points1.clone();
        points.sort();

        let mut arrows = 1;
        let mut end = points[0][1];

        for i in (1..points.len()) {
            if points[i][0] > end {
                arrows += 1;
                end = points[i][1];
            }
            else {
                end = std::cmp::min(end, points[i][1]);
            }            
        }
        arrows
    }
}
```
