:toc:
:toclevels: 4

== link:https://leetcode.com/problems/my-calendar-i/description/[729. My Calendar I]
You are implementing a program to use as your calendar. We can add a new event if adding the event will not cause a double booking.

A double booking happens when two events have some non-empty intersection (i.e., some moment is common to both events.).

The event can be represented as a pair of integers start and end that represents a booking on the half-open interval [start, end), the range of real numbers x such that start <= x < end.

Implement the MyCalendar class:

MyCalendar() Initializes the calendar object.
boolean book(int start, int end) Returns true if the event can be added to the calendar successfully without causing a double booking. Otherwise, return false and do not add the event to the calendar.
 
```
Example 1:
Input
["MyCalendar", "book", "book", "book"]
[[], [10, 20], [15, 25], [20, 30]]
Output
[null, true, false, true]

Explanation
MyCalendar myCalendar = new MyCalendar();
myCalendar.book(10, 20); // return True
myCalendar.book(15, 25); // return False, It can not be booked because time 15 is already booked by another event.
myCalendar.book(20, 30); // return True, The event can be booked, as the first event takes every time less than 20, but not including 20.
```

== Approach-1. map
=== Logic
* Take a ordered map and store <start,end> in it. Values would be arranged in ascending order
* For every incoming interval, iterate over map, if found any overlapping interval break and return false.
* if none of overlapping interval is found. insert and return true

=== Complexity
* Time: O(n)
* Space: O(n)

=== Code
==== CPP
```cpp
class MyCalendar {
    map<int,int> m;
public:
    MyCalendar() {}
    bool book(int a, int b) {
        for (const auto& [i, j] : m) {
            if (a < j && b > i) // If there's an overlap
                return false;
        }
        m.insert({a, b});
        return true;
    }
};

/**
 * Your MyCalendar object will be instantiated and called as such:
 * MyCalendar* obj = new MyCalendar();
 * bool param_1 = obj->book(start,end);
 */
```
