:toc:
:toclevels: 6

== link:https://leetcode.com/problems/difference-between-ones-and-zeros-in-row-and-column/[2482. Difference Between Ones and Zeros in Row and Column]
* You are given a 0-indexed m x n binary matrix grid.
* A 0-indexed m x n difference matrix diff is created with the following procedure:
* Let the number of ones in the ith row be onesRowi.
* Let the number of ones in the jth column be onesColj.
* Let the number of zeros in the ith row be zerosRowi.
* Let the number of zeros in the jth column be zerosColj.
* diff[i][j] = ones_in_Rowi + ones_in_Colj - zeros_in_Rowi - zeros_in_Colj. Return the difference matrix diff.
* example
```c
input = [0 1 1
         1 0 1
         0 0 1]
Output = [0 0 4
          0 0 4
         -2 -2 2]
Input: grid = [[0,1,1],[1,0,1],[0,0,1]]
Output: [[0,0,4],[0,0,4],[-2,-2,2]]
Explanation:
- diff[0][0] = onesRow0 + onesCol0 - zerosRow0 - zerosCol0 = 2 + 1 - 1 - 2 = 0 
- diff[0][1] = onesRow0 + onesCol1 - zerosRow0 - zerosCol1 = 2 + 1 - 1 - 2 = 0 
- diff[0][2] = onesRow0 + onesCol2 - zerosRow0 - zerosCol2 = 2 + 3 - 1 - 0 = 4 
- diff[1][0] = onesRow1 + onesCol0 - zerosRow1 - zerosCol0 = 2 + 1 - 1 - 2 = 0 
- diff[1][1] = onesRow1 + onesCol1 - zerosRow1 - zerosCol1 = 2 + 1 - 1 - 2 = 0 
- diff[1][2] = onesRow1 + onesCol2 - zerosRow1 - zerosCol2 = 2 + 3 - 1 - 0 = 4 
- diff[2][0] = onesRow2 + onesCol0 - zerosRow2 - zerosCol0 = 1 + 1 - 2 - 2 = -2
- diff[2][1] = onesRow2 + onesCol1 - zerosRow2 - zerosCol1 = 1 + 1 - 2 - 2 = -2
- diff[2][2] = onesRow2 + onesCol2 - zerosRow2 - zerosCol2 = 1 + 3 - 2 - 0 = 2
```

== Approach-1. O(mn)
=== Logic
* Count number of 1's in every row and store in vector<int> rows. Number of 0s in particular row=(number of cols - number of 1s in that row)
* Count number of 1's in every col and store in vector<int> cols
* Create diff matrix using the rule

=== Complexity
* Time: O(mn). going twice the array
* Space: O(m) + O(n). Storing number of rows, cols in seperate matrix

=== Code
==== CPP98
```cpp
class Solution {
    void print(vector<int>& onesInRow, vector<int>& onesInCol) {
        for (int i=0;i<onesInRow.size();i++)
            cout << onesInRow[i] << " ";
        cout << "\n";
        for (int i=0;i<onesInCol.size();i++)
            cout << onesInCol[i] << " ";
    }
public:
    vector<vector<int>> onesMinusZeros(vector<vector<int>>& grid) {
        int rows = grid.size();
        int cols = grid[0].size();
        vector<int> onesInRow(rows, 0);
        vector<int> onesInCol(cols, 0);

        //Count 1s in Rows and fill onesInRow
        for (int i=0;i<rows;i++) {
            for (int j=0;j<cols;++j) {
                onesInRow[i] += grid[i][j];
            }
        }

        // Count 1s in coloumns and fill onesInCol
        for (int j=0;j<cols;++j) {
            for (int i=0;i<rows;i++) {
                onesInCol[j] += grid[i][j];
            }
        }

        vector<vector<int>> out(rows, vector<int>(cols,0));
        for (int i=0;i<rows;i++){
            for (int j=0;j<cols;j++){
                out[i][j] = onesInRow[i]+onesInCol[j]-
                            (cols-onesInRow[i]) - (rows-onesInCol[j]);
            }
        }
        return out;
    }
};
```
 
