:toc:
:toclevels: 5


== link:https://leetcode.com/problems/combination-sum-ii/description/[40. Combination Sum II]
* Given a collection of candidate numbers (candidates) and a target number (target), find all unique combinations in candidates where the candidate numbers sum to target.
* Each number in candidates may only be used once in the combination.
* Note: The solution set must not contain duplicate combinations.
```c
Example 1:
Input: candidates = [10,1,2,7,6,1,5], target = 8
Output: [ [1,1,6],  [1,2,5],  [1,7],  [2,6] ]
```

== link:https://youtu.be/12ZdQH1g0QI[Self Video]

== Approach-1, Backtracking
* link:/DS_Questions/Algorithms/Backtracking/[What is Backtracking, BackTracking Template]

=== Logic
- link:/DS_Questions/Algorithms/Backtracking/[BackTracking Template]
1. Create empty candidate list `vector<int> cand`
2. insert element at index=0 into `cand`
3. `if (element > target)` Do not insert element into candidate list.
4. Pass following as parameters in recursive_backtrack function (sum, next index in array).
5. BASE CASE: if (sum == target), insert this combination into final sol array.

<img src=combination_sum_2-bt-tree.jpg width=600 />

==== How to avoid Duplicate combinations in output?
1. sort the input
```c
input = [10,1,2,7,6,1,5]
sorted = [1,1,2,5,6,7,10]

Duplicates can be:
1,2,5   (indexes=0 2 3)
1,2,5   (indexes=1 2 3)
```
2. After sorting, if (prev element = current element), we must have noted all combinations from prev element, Hence do not consider current element.
* `index=0, a[0]=1`. 
* `index=1, a[1]=1`
** Prev element than me was 1, We must have backtracked all combinations and noted the result
```c
start = 0.
- We take combination starting at index=0 (0 2 3)

i = 1
            if (i > start && nums[i] == nums[i - 1])
                continue;
```

=== Code
==== (CPP)Code-1 (Combinations With Duplicates)
```cpp
using vecVecI = vector<vector<int>>;
using vecI = vector<int>;
class Solution {
    vecVecI out;
public:
    void rb(vecI& cand, vecI& nums, int target, int start, int sum) {
        /// Base case
        if (sum > target)
            return;
        if (sum == target) {
            out.push_back(cand);
            return;
        }

        /// Place all candidates
        for (int i=start; i<nums.size(); ++i){
            /// Invalid Candidate
            if (nums[i] > target)
                continue;
                
            /// Place candidate on sol list
            cand.push_back(nums[i]);
            rb (cand, nums, target, i+1, sum+nums[i]);
            
            /// Remove placed candidate from list
            cand.pop_back();
        }
    }
    vecVecI combinationSum2(vecI& nums, int target) {
        /// 1. Start with Empty candidate list
        vecI cand;
        rb (cand, nums, target, 0, 0);
        return out;
    }
};
```

==== CPP(Code-2) (Without Duplicates)
```cpp
using vecVecI = vector<vector<int>>;
using vecI = vector<int>;
class Solution {
    vecVecI out;
public:
    void rb(vecI& cand, vecI& nums, int target, int start, int sum) {
        /// Base case
        if (sum > target)
            return;
        if (sum == target) {
            out.push_back(cand);
            return;
        }

        /// Place candidate on sol list
        for (int i=start; i<nums.size(); ++i){
            if (nums[i]>target)
                continue;
                
            /// Avoid Duplicates
            if (i > start && nums[i] == nums[i - 1])
                continue;
                
            cand.push_back(nums[i]);
            rb (cand, nums, target, i+1, sum+nums[i]);
            
            /// Remove placed candidate from list
            cand.pop_back();
        }
    }
    vecVecI combinationSum2(vecI& nums, int target) {
    
        /// 1. Start with Empty candidate list
        vecI cand;
        
        /// sort to remove duplicates.
        sort(nums.begin(), nums.end());
        rb (cand, nums, target, 0, 0);
        return out;
    }
};
```
==== Rust
```rs
impl Solution {
    pub fn rb(cand: &mut Vec<i32>, nums: &Vec<i32>, target: i32, start: usize, sum: i32, out: &mut Vec<Vec<i32>>) {
        if sum > target {
            return;
        }
        if sum == target {
            out.push(cand.to_vec());
            return;
        }
        for i in start..nums.len() {
            if nums[i] > target {
                break;
            }
            if i > start && nums[i] == nums[i - 1] {
                continue;
            }
            cand.push(nums[i]);
            Self::rb(cand, nums, target, i + 1, sum + nums[i], out);
            cand.pop();
        }
    }

    pub fn combination_sum2(nums: Vec<i32>, target: i32) -> Vec<Vec<i32>> {
        let mut cand: Vec<i32> = Vec::new();
        let mut out: Vec<Vec<i32>> = Vec::new();
        let mut nums = nums;
        nums.sort();
        Self::rb(&mut cand, &nums, target, 0, 0, &mut out);
        out
    }
}
```

=== Complexity
* Time: O(2^n) + O(nlogn)
** Worst case algorithm will exhaust all possible combinations from the input array.
* Space: O(n)
