:toc:
:toclevels: 6

== link:https://leetcode.com/problems/assign-cookies/[455. Assign Cookies]
Assume you are an awesome parent and want to give your children some cookies. But, you should give each child at most one cookie.

Each child i has a greed factor g[i], which is the minimum size of a cookie that the child will be content with; and each cookie j has a size s[j]. If s[j] >= g[i], we can assign the cookie j to the child i, and the child i will be content. Your goal is to maximize the number of your content children and output the maximum number.

```c
Example 1:
Input: g = [1,2,3], s = [1,1]
Output: 1
Explanation: You have 3 children and 2 cookies. The greed factors of 3 children are 1, 2, 3. 
And even though you have 2 cookies, since their size is both 1, you could only make the child whose greed factor is 1 content.
You need to output 1

Example 2:
Input: g = [1,2], s = [1,2,3]
Output: 2
Explanation: You have 2 children and 3 cookies. The greed factors of 2 children are 1, 2. 
You have 3 cookies and their sizes are big enough to gratify all of the children, 
You need to output 2.
```

== Approach-1. Sort and binary search element equal or greater
=== Logic
```c
g = [1,2,3,4,5,6,7,6]      //length=n
s = [17,500,4,5,2,100,12,12]  //length=m
```
* Sort s. s = [2,4,5,12,12,17,100,500]
* iterate through g and binary search every element of g in s. if equal or greater elemenet is found increment count.

=== Complexity
* Time: O(mlogm) + O(nlogm)
* Space: O(1)

=== Code
==== CPP11
```cpp
class Solution {
public:
    int findContentChildren(vector<int>& g, vector<int>& s) {
        sort (s.begin(), s.end());
        int count = 0;
        for_each(g.begin(), g.end(), [&s, &count](int ele){
            auto it = std::lower_bound(s.begin(), s.end(), ele);
            if (it != s.end()) {
                count++;
                s.erase(it);
            }
        });
        return count;
    }
};
```

== Approach-2. Greedy, Sort + 2 pointer
=== Logic
* Intution
** Start from the smallest cookie and try to match it with the smallest child
** If the match is successful, move to the next child and the next larger cookie. 
** This way, you ensure that you use the smallest available cookie for the smallest child, maximizing the number of satisfied children
* sort both g,s. iterate through g,s. if s[i] >= g[i], this child is satisfied. Move to next greater child and next cookie.

=== Complexity
* Time: O(nlogn) + O(mlogm) + O(n)
* Space: O(1)

=== Code
==== CPP
```cpp
class Solution {
public:
    int findContentChildren(vector<int>& g, vector<int>& s) {
        std::sort(g.begin(), g.end());
        std::sort(s.begin(), s.end());

        int childIndex = 0;
        int cookieIndex = 0;
        int count = 0;

        while (childIndex < g.size() && cookieIndex < s.size()) {
            if (s[cookieIndex] >= g[childIndex]) {
                // If the current cookie is equal to or larger than the current child's greed factor
                count++;
                childIndex++;
            }
            cookieIndex++;
        }

        return count;
    }
};
```
