:toc:
:toclevels: 6

== link:https://leetcode.com/problems/number-of-students-unable-to-eat-lunch/[1700. Number of Students Unable to Eat Lunch]
The school cafeteria offers circular and square sandwiches at lunch break, referred to by numbers 0 and 1 respectively. All students stand in a queue. Each student either prefers square or circular sandwiches.

The number of sandwiches in the cafeteria is equal to the number of students. The sandwiches are placed in a stack. At each step:

If the student at the front of the queue prefers the sandwich on the top of the stack, they will take it and leave the queue.
Otherwise, they will leave it and go to the queue's end.
This continues until none of the queue students want to take the top sandwich and are thus unable to eat.

You are given two integer arrays students and sandwiches where sandwiches[i] is the type of the i​​​​​​th sandwich in the stack (i = 0 is the top of the stack) and students[j] is the preference of the j​​​​​​th student in the initial queue (j = 0 is the front of the queue). Return the number of students that are unable to eat.
```c
Example 1:
Input: students = [1,1,0,0], sandwiches = [0,1,0,1]
Output: 0 
Explanation:
- Front student leaves the top sandwich and returns to the end of the line making students = [1,0,0,1].
- Front student leaves the top sandwich and returns to the end of the line making students = [0,0,1,1].
- Front student takes the top sandwich and leaves the line making students = [0,1,1] and sandwiches = [1,0,1].
- Front student leaves the top sandwich and returns to the end of the line making students = [1,1,0].
- Front student takes the top sandwich and leaves the line making students = [1,0] and sandwiches = [0,1].
- Front student leaves the top sandwich and returns to the end of the line making students = [0,1].
- Front student takes the top sandwich and leaves the line making students = [1] and sandwiches = [1].
- Front student takes the top sandwich and leaves the line making students = [] and sandwiches = [].
Hence all students are able to eat.

Example 2:
Input: students = [1,1,1,0,0,1], sandwiches = [1,0,0,0,1,1]
Output: 3
```

== Approach-1.
=== Logic
* Count number of 1's & 0's in student array. ie how many students want to eat 1 or 0 sandwich. Also fill students in queue.
```c
student =  [1,1,1,0,0,1]    //fill students in queue
sandwich = [1,0,0,0,1,1]
students_like_1 = 4
students_like_0 = 2

      queue      sandwich      students_like_1      students_like_0
1 1 1 0 0 1     1 0 0 0 1 1          4                    2
                p
```
* if front of queue == sandwich. Remove queue. Increment sandwich pointer and reduce count of like student
```c
      queue      sandwich      students_like_1      students_like_0
1 1 1 0 0 1     1 0 0 0 1 1          4                    2
                p

1 1 0 0 1     1 0 0 0 1 1          3                    2
                p
sandwich[p] != queue.front()
```
* Push elements at back of queue until its not equal to sandwich front
```c
   queue      sandwich      students_like_1      students_like_0
0 0 1 1 1     1 0 0 0 1 1          3                    2
                p

    1 1 1     1 0 0 0 1 1          3                    0
                    p
```
* if there is a sandwich at front which is not liked by any student(ie students liking that kind of sandwich=0) then return number of students left in queue
```c
if (students_like_0 == 0 and sandwich[p] == 0)
  return queue.size()
```

=== Complexity
* Time: O(n)
* Space: O(n). Creating queue

=== Code
==== CPP
```cpp
class Solution {
public:
    int countStudents(vector<int>& students, vector<int>& sandwiches) {
        int student_want_0 = 0, student_want_1 = 0;
        queue<int> q;
        // Push students on queue and count liking students
        for (auto&i:students) {
            if (i==0)
                student_want_0++;
            else
                student_want_1++;
            q.push(i);
        }

        int p = 0;
        while (!q.empty() && p<students.size()) {
            while (sandwiches[p] == q.front()) {
                if (q.front() == 0)
                    student_want_0--;
                else 
                    student_want_1--;
                p++;
                q.pop();
                if (q.empty())
                    return 0;                
            }
            if(student_want_0==0 && sandwiches[p]==0 ||
               student_want_1==0 && sandwiches[p]==1)
                return q.size();
            while(sandwiches[p] != q.front()) {
                q.push(q.front());
                q.pop();
            }
        }
        return 0;
    }
};
```
