:toc:
:toclevels: 6

=== Monotonic Stack vs Queue
|===
| | Monotonic Stack | Monotonic Queue |

| Applications |To Find next greater element / next smaller element / Previous greater element / and previous smaller element | Find min/max in the current sliding window |
|===

=== Monotonic Queue
Used to find Min/Max in sliding Window

==== Types of Queues
|===
| | Increasing Monotonic Queue | Decreasing Monotonic Queue |

|Order of elements in queue| Increasing | Decreasing |
|Removing from Queue| Any element that is smaller than the current minimum is removed | Any element that is greater than the current max is removed | 
|===

===== Increasing Monotonic Queue
* This will store longest incresing link:DS_Questions/Questions/vectors_arrays/SubSequence_SubArray[Sub-sequence]
* Example
```c
input = { 1, 3, -1, -3, 5, 3, 6, 7}
Monotonic Increasing Queue = {-3, 3, 6, 7}

//Code
/*
input=  | 1, 3, -1, -3, 5, 3, 6, 7 |
          0  1   2   3  4  5  6  7
  i   monotonic_queue
  0   1
  1   1     3
      front back
      
  2   (3 > -1). Remove 3
      (1 > -1). Remove 1
      
  3   -3
  4   -3     5
      front back
      
  5   (5 > 3). Remove 3
      -3  3
  6   -3  3   6
  7   -3  3   6   7
  
  //Note monotonic Queue contains all increasing Sub-Sequences.
  //Finally Queue keeps longest increasing Sub-Sequence.
*/
deque<int> increasing_monotonic_queue(vector<int>& v) {
    deque<int> q;
    for (auto&i: v) {
        while (!q.empty() && q.back() > arr[i]) 
            q.pop_back();
            
        q.push_back(i);
    }
    return q;
}

int main() {
  vector<int> v =  { 1, 3, -1, -3, 5, 3, 6, 7};
  deque<int> q = increasing_monotonic_queue(v);
  for (int i : q)
      cout << i << " ";           //-3 5 6 7
  return 0;
}
```

=== Monotonic Stack
* This contains increasing subsequence or decreasing subsequence(BUT NOT LONGEST/SMALLEST) and done in O(nm) time.
** n:Number of input elements, m:
* We create stack from input array.
```c
Input array = {2, 3, 7, 11, 5, 17, 19}
Monotonic Increasing Stack
|19|
|17|
|5 |
|3 |
|2 |
```

==== Increasing subseqeunce
* 1. if stack is empty, insert element.
* 2. if 
** (ele > stack.top())
*** insert element
** else
*** remove all greater elements
```c
arr = {2, 3, 7, 11, 5, 17, 19}
  arr_ele   stack
    2       |2|
    3       |3|     //3>2
            |2|
    7       |7|     //7>3
            |3|
            |2|
    11      |11|     //11>7
            |7|
            |3|
            |2|
    5       |11|     //element(5) < top(11). pop
            |7|
            |3|
            |2|
            
            |7|     //element(5) < top(7). pop
            |3|
            |2|
            
            |3|     //element(5) > top(3). push
            |2|

            |5|
            |3|
            |2|

    17      |17|     //17 > 5. Push
            |5|
            |3|
            |2|

    19      |19|     //19 > 17. Push
            |17|
            |5|
            |3|
            |2|
```
- _3._ Our stack contains increasing subsequence.
```c
{2, 3, 7, 11, 5, 17, 19}
Longest Increasing subsequence: {2,3,7,11,17,19}
Monotonic stack contains:       2,3,5,17,19
```

===== Code
```cpp
int main() {
    vector<int> arr = {2,3,7,11,5,17,19};

    stack<int> st;
    for (int i=0;i<arr.size();++i){
        while (!st.empty() && st.top() >= arr[i])
            st.pop();
        st.push(arr[i]);
    }
    while(!st.empty()){
        cout << st.top() <<" ";   st.pop();
    }
    cout <<"\n";
}
```
