:toc:
:toclevels: 6

== link:https://leetcode.com/problems/number-of-laser-beams-in-a-bank/[2125. Number of Laser Beams in a Bank]
Anti-theft security devices are activated inside a bank. You are given a 0-indexed binary string array bank representing the floor plan of the bank, which is an m x n 2D matrix. bank[i] represents the ith row, consisting of '0's and '1's. '0' means the cell is empty, while'1' means the cell has a security device.

There is one laser beam between any two security devices if both conditions are met:

The two devices are located on two different rows: r1 and r2, where r1 < r2.
For each row i where r1 < i < r2, there are no security devices in the ith row.
Laser beams are independent, i.e., one beam does not interfere nor join with another.

Return the total number of laser beams in the bank.

```c
Input: bank = ["011001","000000","010100","001000"]
Output: 8
Explanation: Between each of the following device pairs, there is one beam. In total, there are 8 beams:
 * bank[0][1] -- bank[2][1]
 * bank[0][1] -- bank[2][3]
 * bank[0][2] -- bank[2][1]
 * bank[0][2] -- bank[2][3]
 * bank[0][5] -- bank[2][1]
 * bank[0][5] -- bank[2][3]
 * bank[2][1] -- bank[3][2]
 * bank[2][3] -- bank[3][2]
Note that there is no beam between any device on the 0th row with any on the 3rd row.
This is because the 2nd row contains security devices, which breaks the second condition.
```

== Approach-1. O(n). Count number of 1's in each string
=== Logic
* Traverse every string, count number of 1's in string. if no 1's are present skip the row
* Store count of 1's in seperate vector<int>
```c
bank = ["011001","000000","010100","001000"]
1's  =    3        skip      2      1
     =    3, 2, 1
```
* Multiple consecutive numbers in vector and add all
```c
out =  3*2 + 2*1  =  8
```

=== Complexity
* Time: O(nm). n=strings, m=length of each
* Space: O(n)

=== Code
==== CPP11
```cpp
class Solution {
public:
    int numberOfBeams(vector<string>& bank) {
        vector<int> ones;
        for_each(bank.begin(), bank.end(), [&ones](string row){
            int count = 0;
            for(char& ch: row) {
                if (ch == '1')
                    count++;
            }
            if (count)
                ones.push_back(count);
        });
        int out=0;
        // Use loop with iterators
        if (ones.size()) {
            for (auto it=ones.begin(); it!=ones.end()-1; ++it) {
                auto next = std::next(it);
                out += (*it)*(*next);
            }
        }
        return out;
    }
};
```
