:toc:
:toclevels: 6

== sidecar / istio / service mesh
* In kubernets istio (or service mesh) is advanced platform which provides networking, security capabilities to microservices.
* It places a seperate container (called sidecar or Envoy) inside the pod along side with existing application service.

=== Usage of sidecar / Envoy
* it acts as intermediary between microservice and rest of the system.
* Istio sidecar intercepts all communication between microservice and rest of services and provide routing, policy enforcement, telemetry, TLS to traffic

```mermaid
flowchart TB

    subgraph POD1
       subgraph container_b
            istio_sidecar1
        end
        subgraph container_a
            microservice1
        end
    end

    subgraph POD2
        subgraph container_c
            microservice2
        end
        subgraph container_d
            istio_sidecar2
        end
    end

    container_a <--"HTTP"--> container_b
    container_c <--"HTTP"--> container_d
    container_d <--"HTTPS"--> container_b
```

=== Istio AuthorizationPolicy
* Used to define access control policies for service-to-service communication within the Istio service mesh. Allows to specify rules for controlling which services are allowed to communicate with each other and under what conditions.
* *Usage?* To enforce fine-grained access control, including scenarios where certain services should only be accessible by specific other services.
* Example
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: example-auth-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-service
  action: ALLOW                    //////////// Rule: test-service allows any source(*) to make HTTP GET reqest.
  rules:
  - from:
    - source:
        principals: ["*"]
    to:
    - operation:
        methods: ["GET"]
```
